-- CERT-IMP01: Certificado-only, version-bound, single-use mobile signature sessions.
CREATE TABLE IF NOT EXISTS clinical_certificado_qr_sessions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  token CHAR(64) NOT NULL,
  document_uuid CHAR(36) NOT NULL,
  document_version INT NOT NULL,
  patient_id VARCHAR(128) NOT NULL,
  doctor_id VARCHAR(64) NOT NULL,
  actor_user_id VARCHAR(64) NOT NULL,
  role VARCHAR(16) NOT NULL,
  signer_authority VARCHAR(512) NOT NULL,
  signer_name VARCHAR(191) NOT NULL,
  signer_role_label VARCHAR(64) NOT NULL,
  fingerprint_version TINYINT NOT NULL DEFAULT 1,
  content_fingerprint CHAR(64) NOT NULL,
  review_html MEDIUMTEXT NOT NULL,
  review_html_sha256 CHAR(64) NOT NULL,
  signature_image_data MEDIUMTEXT DEFAULT NULL,
  artifact_digest CHAR(64) DEFAULT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL,
  expires_at DATETIME NOT NULL,
  reviewed_at DATETIME DEFAULT NULL,
  uploaded_at DATETIME DEFAULT NULL,
  consumed_at DATETIME DEFAULT NULL,
  invalidated_at DATETIME DEFAULT NULL,
  claimed_document_uuid CHAR(36) DEFAULT NULL,
  UNIQUE KEY uq_certificado_qr_token (token),
  KEY idx_certificado_qr_document (document_uuid, role, status),
  KEY idx_certificado_qr_expiry (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
