import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
export async function runGalleryVisualQA({base,tokens,gallery,sql,grant,revoke}){
 const output='/tmp/mxmed-mr10-visual';await mkdir(output,{recursive:true});const version=await(await fetch((process.env.CDP_URL||'http://127.0.0.1:9348')+'/json/version')).json();
 let failAt=0,seenApprovals=0;
 const ws=new WebSocket(version.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let seq=0,sessionId,contextId;const pending=new Map(),requests=[];
 const send=(method,params={},session=sessionId)=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params,...(session?{sessionId:session}:{})}));});
 ws.addEventListener('message',event=>{const m=JSON.parse(event.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p?.reject(new Error(JSON.stringify(m.error))):p?.resolve(m.result);}else if(m.method==='Network.requestWillBeSent')requests.push(m.params.request);else if(m.method==='Fetch.requestPaused'){seenApprovals++;if(failAt&&seenApprovals===failAt)send('Fetch.fulfillRequest',{requestId:m.params.requestId,responseCode:503,responseHeaders:[{name:'Content-Type',value:'application/json'}],body:btoa(JSON.stringify({ok:false,error:'unavailable'}))}).catch(()=>{});else send('Fetch.continueRequest',{requestId:m.params.requestId}).catch(()=>{});}});
 const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
 const until=async expression=>{for(let i=0;i<160;i++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,50));}throw new Error('Timeout '+expression);};
 const key=async(name,code)=>{await send('Input.dispatchKeyEvent',{type:'keyDown',key:name,code:name,windowsVirtualKeyCode:code,...(name==='Enter'?{text:'\r',unmodifiedText:'\r'}:{})});await send('Input.dispatchKeyEvent',{type:'keyUp',key:name,code:name,windowsVirtualKeyCode:code});};
 const click=async id=>{await evaluate(`document.getElementById('${id}').focus()`);if(await evaluate(`document.getElementById('${id}').type==='checkbox'`)){await send('Input.dispatchKeyEvent',{type:'keyDown',key:' ',code:'Space',windowsVirtualKeyCode:32});await send('Input.dispatchKeyEvent',{type:'keyUp',key:' ',code:'Space',windowsVirtualKeyCode:32});}else await key('Enter',13);};
 const shot=async name=>{const r=await send('Page.captureScreenshot',{format:'png'});await writeFile(output+'/'+name+'.png',Buffer.from(r.data,'base64'));};
 const pixel=async(id,x,y)=>evaluate(`(()=>{const i=document.getElementById('${id}'),c=document.createElement('canvas');c.width=i.naturalWidth;c.height=i.naturalHeight;const ctx=c.getContext('2d');ctx.drawImage(i,0,0);return Array.from(ctx.getImageData(Math.floor(c.width*${x}),Math.floor(c.height*${y}),1,1).data)})()`);
 try{
  contextId=(await send('Target.createBrowserContext',{},null)).browserContextId;const target=(await send('Target.createTarget',{url:'about:blank',browserContextId:contextId},null)).targetId;sessionId=(await send('Target.attachToTarget',{targetId:target,flatten:true},null)).sessionId;
  await send('Page.enable');await send('Runtime.enable');await send('Network.enable');await send('Page.bringToFront');
  const cookie=async value=>send('Network.setCookie',{name:'__Host-mxmed_session',value,url:base,path:'/',secure:true,httpOnly:true,sameSite:'Lax'});await cookie(tokens.good);
  for(const [width,height] of [[1440,900],[1366,768],[390,844],[320,740]])for(const [n,mixed] of [[1,false],[4,false],[16,false],[4,true]]){
   const first=gallery(),items=[first];for(let i=1;i<n;i++)items.push(gallery(first.doctor));
   if(mixed)sql('require_once "modules/media/tests/GalleryReviewFixture.php";mr5Candidate($p);mr7Candidate($p);');
   const start=requests.length;await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<500});await send('Page.navigate',{url:base+'/internal/media-review/'});await until("document.querySelectorAll('.gallery-select input').length==="+n+"&&!document.getElementById('gallery-bulk').hidden");
   assert.equal(await evaluate("[...document.querySelectorAll('.review-thumb img')].every(i=>i.loading==='lazy'&&getComputedStyle(i).objectFit==='contain')"),true,'lazy contain');assert.equal(await evaluate("document.documentElement.innerHTML.includes('data:image')"),false);assert.equal(requests.slice(start).some(r=>r.url.includes('source-download')),false,'no source in list');
   await evaluate("document.querySelector('.gallery-select').closest('.card').querySelector('button').click()");await until("document.querySelector('dialog').open && document.getElementById('detail-image').naturalWidth>0");assert.equal(await evaluate("document.getElementById('detail-purpose').textContent"),'Foto de galería');assert.equal(await evaluate("document.getElementById('logo-improvement').hidden"),true);assert.equal(await evaluate("document.getElementById('request-replacement').hidden||document.getElementById('design-intervention').hidden"),false);await shot(width+'-'+n+(mixed?'-mixed':'')+'-detail');await click('close-detail');
   await until("!document.querySelector('dialog').open && document.activeElement.closest('.card')!==null");await click('select-page-gallery');assert.equal(await evaluate("document.querySelectorAll('.gallery-select input:checked').length"),n);assert.equal(await evaluate("document.getElementById('approve-selected-gallery').textContent"),'Aprobar seleccionadas ('+n+')');
   if(mixed)assert.equal(await evaluate("[...document.querySelectorAll('.card')].filter(c=>!c.querySelector('.gallery-select')).length"),2,'photo_logo_not_selectable');
   const expected=await evaluate("[...document.querySelectorAll('.gallery-select input:checked')].map(i=>i.value)");
   let partial=false,hard=false;
   if(n===4&&!mixed&&width===1440){sql(`require_once "modules/media/tests/GalleryReviewFixture.php";[$private,$public]=mr5Storage();(new Media\\Services\\GalleryApprovalService($p,$private,$public))->approve(mr5Context(),'${expected[0]}');`);partial=true;}
   if(n===4&&!mixed&&width===1366){failAt=2;seenApprovals=0;await send('Fetch.enable',{patterns:[{urlPattern:'*approve-gallery.php*',requestStage:'Request'}]});hard=true;}
   const posts=requests.filter(r=>r.method==='POST'&&r.url.endsWith('approve-gallery.php')).length;
   assert.equal(await evaluate("(()=>{document.getElementById('approve-selected-gallery').click();return document.getElementById('approve-selected-gallery').disabled&&document.getElementById('select-page-gallery').disabled})()"),true,'busy guards');
   await until("document.getElementById('inbox-message').textContent.startsWith('Se confirmó la aprobación de ')");if(hard){await send('Fetch.disable');failAt=0;}
   const confirmed=hard?1:partial?n-1:n;assert.ok((await evaluate("document.getElementById('inbox-message').textContent")).includes(confirmed+' de '+n));
   const calls=requests.filter(r=>r.method==='POST'&&r.url.endsWith('approve-gallery.php')).slice(posts);assert.equal(calls.length,hard?2:n);assert.deepEqual(calls.map(r=>JSON.parse(r.postData).submission_id),expected.slice(0,calls.length),'deterministic order');
   assert.equal(Number(sql(`echo $p->query("SELECT COUNT(*) FROM media_assets WHERE owner_id='${first.doctor}' AND purpose='DOCTOR_GALLERY' AND status='READY'")->fetchColumn();`)),hard?1:n);
   assert.equal(await evaluate("document.documentElement.scrollWidth<=innerWidth"),true,'no overflow');await shot(width+'-'+n+(mixed?'-mixed':'')+'-result');
   sql("$p->exec(\"UPDATE media_review_submissions SET review_status='WITHDRAWN' WHERE review_status='PENDING_REVIEW'\");");
  }
  const a=gallery(),b=gallery();for(let i=1;i<16;i++){gallery(a.doctor);gallery(b.doctor);}
  await send('Page.navigate',{url:base+'/internal/media-review/'});await until("document.querySelectorAll('.gallery-select input').length===25&&!document.getElementById('gallery-bulk').hidden");await click('select-page-gallery');assert.equal(await evaluate("document.querySelectorAll('.gallery-select input:checked').length"),25,'current_page_only');await click('approve-selected-gallery');await until("document.getElementById('inbox-message').textContent.includes('25 de 25')");assert.equal(await evaluate("document.querySelectorAll('.gallery-select input').length"),7,'next_page_items_not_selected');
  await cookie(tokens.wrong);await send('Page.navigate',{url:base+'/internal/media-review/'});await until("document.querySelector('.card')");assert.equal(await evaluate("document.getElementById('gallery-bulk').hidden&&[...document.querySelectorAll('.gallery-select')].every(i=>i.hidden)"),true,'read_only_no_selection');
  console.log('MR10_VISUAL_QA=PASS: four viewports x 1/4/16/mixed; contain/lazy/private; gallery-only selection; independent sequential approvals; real 409 partial success; hard failure stops; current-page-only; keyboard/focus/busy/no overflow');
 }finally{if(contextId)await send('Target.disposeBrowserContext',{browserContextId:contextId},null);ws.close();}
}
