import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
export async function runImprovementVisualQA({base,tokens,candidate,sql,grant,revoke}){
 const output='/tmp/mxmed-mr8-visual';await mkdir(output,{recursive:true});const version=await(await fetch((process.env.CDP_URL||'http://127.0.0.1:9348')+'/json/version')).json();
 const ws=new WebSocket(version.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let seq=0,sessionId,contextId;const pending=new Map(),requests=[];
 const send=(method,params={},session=sessionId)=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params,...(session?{sessionId:session}:{})}));});
 ws.addEventListener('message',event=>{const m=JSON.parse(event.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p?.reject(new Error(JSON.stringify(m.error))):p?.resolve(m.result);}else if(m.method==='Network.requestWillBeSent')requests.push(m.params.request);else if(m.method==='Fetch.requestPaused')send('Fetch.failRequest',{requestId:m.params.requestId,errorReason:'Failed'}).catch(()=>{});});
 const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
 const until=async expression=>{for(let i=0;i<160;i++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,50));}throw new Error('Timeout '+expression);};
 const key=async(name,code)=>{await send('Input.dispatchKeyEvent',{type:'keyDown',key:name,code:name,windowsVirtualKeyCode:code,...(name==='Enter'?{text:'\r',unmodifiedText:'\r'}:{})});await send('Input.dispatchKeyEvent',{type:'keyUp',key:name,code:name,windowsVirtualKeyCode:code});};
 const click=async id=>{await evaluate(`document.getElementById('${id}').focus()`);await key('Enter',13);};
 const shot=async name=>{const r=await send('Page.captureScreenshot',{format:'png'});await writeFile(output+'/'+name+'.png',Buffer.from(r.data,'base64'));};
 const pixel=async(id,x,y)=>evaluate(`(()=>{const i=document.getElementById('${id}'),c=document.createElement('canvas');c.width=i.naturalWidth;c.height=i.naturalHeight;const ctx=c.getContext('2d');ctx.drawImage(i,0,0);return Array.from(ctx.getImageData(Math.floor(c.width*${x}),Math.floor(c.height*${y}),1,1).data)})()`);
 try{
  contextId=(await send('Target.createBrowserContext',{},null)).browserContextId;const target=(await send('Target.createTarget',{url:'about:blank',browserContextId:contextId},null)).targetId;sessionId=(await send('Target.attachToTarget',{targetId:target,flatten:true},null)).sessionId;
  await send('Page.enable');await send('Runtime.enable');await send('Network.enable');await send('Page.bringToFront');
  const cookie=async value=>send('Network.setCookie',{name:'__Host-mxmed_session',value,url:base,path:'/',secure:true,httpOnly:true,sameSite:'Lax'});await cookie(tokens.good);
  for(const [width,height] of [[1440,900],[1366,768],[390,844],[320,740]])for(const [label,kind,w,h] of [['horizontal','white',600,240],['square','white',400,400],['tall','white',200,600],['white-background','white',500,300],['off-white','offwhite',500,300],['transparent','transparent',500,300],['white-interior','white',600,300]]){
   const f=candidate(kind,w,h),oldLogo=sql(`echo $p->query("SELECT logo_url FROM profiles_doctors WHERE doctor_id='${f.doctor}'")->fetchColumn();`);
   await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<500});await send('Page.navigate',{url:base+'/internal/media-review/'});await until("document.querySelector('.card button')");await evaluate("document.querySelector('.card button').click()");
   await until("document.getElementById('detail-image').naturalWidth>0 && !document.getElementById('logo-improvement').hidden");
   const posts=requests.filter(r=>r.method==='POST').length;await click('generate-improvement');
   // Programmatic second activation while request is running must not create another proposal.
   await evaluate("document.getElementById('generate-improvement').click()");
   if(kind==='transparent'){
    await until("document.getElementById('improvement-message').textContent==='No se detectó una mejora automática segura.'");assert.equal(await evaluate("document.getElementById('proposal-panel').hidden"),true);await shot(width+'-'+label);await click('close-detail');sql(`$p->exec("UPDATE media_review_submissions SET review_status='WITHDRAWN' WHERE submission_id='${f.id}'");`);continue;
   }
   await until("!document.getElementById('accept-improvement').disabled && !document.getElementById('proposal-panel').hidden && document.getElementById('proposal-image').naturalWidth>0");
   assert.equal(requests.filter(r=>r.method==='POST').length,posts+1,'single generation');assert.equal(await evaluate("document.getElementById('detail-image').hidden"),false);
   assert.equal((await pixel('detail-image',0,0))[3],255,'current still opaque');assert.equal((await pixel('proposal-image',0,0))[3],0,'proposal exterior alpha');const interior=await pixel('proposal-image',.5,.5);assert.equal(interior[3],255);assert.ok(interior.slice(0,3).every(c=>c>240),'interior white preserved');
   assert.equal(await evaluate("['detail-image','proposal-image'].every(id=>getComputedStyle(document.getElementById(id)).objectFit==='contain')"),true);
   assert.equal(await evaluate("(()=>{const d=document.querySelector('dialog'),r=d.getBoundingClientRect();return document.documentElement.scrollWidth<=innerWidth&&d.scrollWidth<=d.clientWidth&&r.left>=0&&r.right<=innerWidth})()"),true,'no overflow');
   await evaluate("document.getElementById('improvement-comparison').scrollIntoView({block:'start'})");await shot(width+'-'+label+'-comparison');
   assert.equal(sql(`echo $p->query("SELECT logo_url FROM profiles_doctors WHERE doctor_id='${f.doctor}'")->fetchColumn();`),oldLogo);
   if(label==='square'){await click('discard-improvement');await until("document.getElementById('improvement-message').textContent.includes('Propuesta descartada')");assert.equal((await pixel('detail-image',0,0))[3],255);await click('generate-improvement');await until("!document.getElementById('accept-improvement').disabled && document.getElementById('proposal-image').naturalWidth>0");}
   await click('accept-improvement');await until("document.getElementById('improvement-message').textContent.includes('Versión mejorada lista') && !document.getElementById('approve-photo').disabled");assert.equal((await pixel('detail-image',0,0))[3],0);assert.equal(sql(`echo $p->query("SELECT logo_url FROM profiles_doctors WHERE doctor_id='${f.doctor}'")->fetchColumn();`),oldLogo,'accept not public');assert.equal(sql(`echo $p->query("SELECT review_status FROM media_review_submissions WHERE submission_id='${f.id}'")->fetchColumn();`),'PENDING_REVIEW');
   await click('approve-photo');await until("!document.getElementById('approval-confirmation').hidden");await click('confirm-approval');await until("document.getElementById('inbox-message').textContent==='Logotipo aprobado y publicado.'");
  }
  const failure=candidate();await send('Page.navigate',{url:base+'/internal/media-review/'});await until("document.querySelector('.card button')");await evaluate("document.querySelector('.card button').click()");await until("!document.getElementById('logo-improvement').hidden && document.getElementById('detail-image').naturalWidth>0");await click('generate-improvement');await until("!document.getElementById('accept-improvement').disabled");
  await send('Page.navigate',{url:base+'/internal/media-review/'});await until("document.querySelector('.card button')");await evaluate("document.querySelector('.card button').click()");await until("!document.getElementById('proposal-panel').hidden && !document.getElementById('accept-improvement').disabled");
  await send('Fetch.enable',{patterns:[{urlPattern:'*improvement-preview.php*',requestStage:'Request'}]});await click('generate-improvement');await until("document.getElementById('improvement-message').textContent.includes('No fue posible completar')");assert.equal(await evaluate("document.getElementById('proposal-panel').hidden && document.getElementById('accept-improvement').disabled && document.getElementById('approve-photo').disabled"),true,'failed new preview never accepts old proposal');await shot('320-preview-failure');await send('Fetch.disable');sql(`$p->exec("UPDATE media_review_submissions SET review_status='WITHDRAWN' WHERE submission_id='${failure.id}'");`);
  candidate();await cookie(tokens.wrong);await send('Page.navigate',{url:base+'/internal/media-review/'});await until("document.querySelector('.card button')");await evaluate("document.querySelector('.card button').click()");await until("document.querySelector('dialog').open");assert.equal(await evaluate("document.getElementById('logo-improvement').hidden"),true,'read only');await key('Escape',27);await until("!document.querySelector('dialog').open");
  sql("$p->exec(\"UPDATE media_review_submissions SET review_status='WITHDRAWN' WHERE review_status='PENDING_REVIEW'\");echo json_encode(mr5Candidate($p));");
  await cookie(tokens.good);await send('Page.navigate',{url:base+'/internal/media-review/'});await until("document.querySelector('.card button')");await evaluate("document.querySelector('.card button').click()");await until("document.getElementById('detail-image').naturalWidth>0");assert.equal(await evaluate("document.getElementById('logo-improvement').hidden"),true,'photo has no improvement control');
  console.log('MR8_VISUAL_QA=PASS: 28 viewport/fixture combinations; alpha and white interior pixels; current/proposal; keyboard; discard/accept/explicit publication; no overflow; '+output);
 }catch(e){await shot('failure');console.error(await evaluate("document.getElementById('improvement-message')?.textContent"));throw e;}
 finally{if(contextId)await send('Target.disposeBrowserContext',{browserContextId:contextId},null);ws.close();}
}
