import base64, hashlib, json, os, re, subprocess
from playwright.sync_api import sync_playwright, expect
BASE=os.environ['FLOW_R1_QA_BASE']; DB=os.environ['FLOW_R1_QA_DB']
assert re.fullmatch(r'flow_r1_qa_[0-9a-f]{12}', DB)
assert re.fullmatch(r'http://127\.0\.0\.1:\d+', BASE)
with open('modules/clinical/db/migrations/2026_10_06_29_consent_templates.sql') as migration:
    subprocess.run(['mysql',DB],input=migration.read(),text=True,check=True)
def check(n,v):
    if not v: raise AssertionError(n)
    print(n+'=PASS',flush=True)
def payload():
    sql="SELECT payload_json FROM clinical_documents WHERE document_type='consentimiento_informado' ORDER BY id DESC LIMIT 1"
    raw=subprocess.check_output(['mysql','--raw','-N','-B',DB,'-e',sql],text=True)
    return json.loads(raw)
def draw(page,selector):
    page.locator(selector).scroll_into_view_if_needed()
    box=page.locator(selector).bounding_box();x=box['x'];y=box['y']
    page.mouse.move(x+25,y+25);page.mouse.down();page.mouse.move(x+140,y+65,steps=8);page.mouse.up()
def go_signatures(page):
    page.locator('#ci_preview').click()
    expect(page.locator('#ci_review_panel')).to_be_visible()
    page.locator('#ci_review_continue').click()
    expect(page.locator('#ci_signatures_panel')).to_be_visible()
def save(page):
    page.locator('#ci_review_confirm_informed').check()
    page.locator('#ci_signatures_continue').click()
    expect(page.locator('#ci_review_heading')).to_have_text('Vista previa · Revisión final')
    with page.expect_response(lambda r:r.request.method=='POST' and '/patients/p_plan02ux_review/documents' in r.url) as response:
        page.locator('#ci_save').click()
    check('SAVE_HTTP',response.value.status in (200,201))
    expect(page.locator('#modalConsentimientoInformado')).to_be_hidden()
def open_draft(page):
    page.locator('[data-action="documents-open-consent"]').click()
    expect(page.locator('#modalConsentDraftPrompt')).to_be_visible()
    page.locator('#modalConsentDraftPrompt [data-draft-ref]').first.click()
    expect(page.locator('#modalConsentimientoInformado')).to_be_visible()
    go_signatures(page)
def reload_to_draft(page):
    page.goto(BASE+'/index.html?qa_tools=hide',wait_until='domcontentloaded')
    page.wait_for_function('typeof window.setActivePatientId === "function"')
    page.evaluate("window.__MXMED_USER_ID='review-user';window.mxmedStore.user_id='review-user'")
    page.evaluate("async()=>{await window.setActivePatientId('p_plan02ux_review',{emitEvent:true,skipM7DirtyGuard:true,skipActiveEncounterConfirm:true,skipUnsavedNewPatientConfirm:true,applyEntryRule:false});document.querySelector('#p-expediente').classList.remove('d-none');window.dispatchEvent(new Event('patient:selected'))}")
    page.locator('#p-expediente [data-exp-tabs] [data-bs-target="#t-consent"]').click()
    page.locator('#t-consent .docvis-intents').first.locator('button').first.click()
    page.locator('#t-consent .docvis-intents').nth(1).locator('button').first.click()
    open_draft(page)
with sync_playwright() as pw:
    browser=pw.webkit.launch(headless=True)
    page=browser.new_page(viewport={'width':1440,'height':900},extra_http_headers={'Cookie':'PHPSESSID=step3-head-neck-qa'})
    errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto(BASE+'/index.html?qa_tools=hide',wait_until='domcontentloaded')
    page.wait_for_function('typeof window.setActivePatientId === "function"')
    page.evaluate("window.__MXMED_USER_ID='review-user';window.mxmedStore.user_id='review-user'")
    page.evaluate("async()=>{await window.setActivePatientId('p_plan02ux_review',{emitEvent:true,skipM7DirtyGuard:true,skipActiveEncounterConfirm:true,skipUnsavedNewPatientConfirm:true,applyEntryRule:false});document.querySelector('#p-expediente').classList.remove('d-none');window.dispatchEvent(new Event('patient:selected'))}")
    page.locator('#p-expediente [data-exp-tabs] [data-bs-target="#t-consent"]').click()
    page.locator('#t-consent .docvis-intents').first.locator('button').first.click()
    page.locator('#t-consent .docvis-intents').nth(1).locator('button').first.click()
    page.locator('[data-action="documents-open-consent"]').click()
    page.locator('#modalConsentTemplateFlow [data-tpl-action="blank"]').click()
    page.locator('#ci_next').click()
    page.locator('#ci_title').fill('Prueba CONS-SIGN02A')
    page.locator('#ci_procedimiento').fill('Biopsia de piel')
    go_signatures(page)
    check('T05_BLANK_PATIENT',page.locator('#ci_signature_status').inner_text()=='Sin firma')
    check('T08_BLANK_DOCTOR',page.locator('#ci_doctor_signature_status').inner_text() in ['Sin firma','Firma registrada disponible'])
    box=page.locator('#ci_signature_canvas').bounding_box();page.mouse.click(box['x']+40,box['y']+40)
    check('T06_CLICK_ONLY',page.locator('#ci_signature_status').inner_text()=='Sin firma')
    page.mouse.move(box['x']+50,box['y']+50);page.mouse.down();page.mouse.move(box['x']+51,box['y']+51);page.mouse.up()
    check('T06_TINY_POINT',page.locator('#ci_signature_status').inner_text()=='Sin firma')
    save(page)
    p=payload();check('T01_DRAFT_NO_SIGNATURES',p['signature_binding_status']=={'patient':'absent','doctor':'absent'})
    first_date=p['signature_document_date']
    open_draft(page)
    page.locator('#ci_review_confirm_informed').check()
    draw(page,'#ci_signature_canvas')
    page.wait_for_function("document.querySelector('#ci_signature_status').textContent.includes('vinculada')",timeout=15000)
    check('T04_REAL_PATIENT',page.locator('#ci_signature_status').inner_text()=='Firma vinculada a esta versión')
    save(page)
    p=payload();check('T02_PATIENT_ONLY',p['signature_binding_status']=={'patient':'valid_bound_signature','doctor':'absent'})
    check('T12_PATIENT_METADATA',p['signatures']['patient']['binding']['version']==1)
    open_draft(page)
    page.wait_for_function("document.querySelector('#ci_signature_status').textContent.includes('vinculada')",timeout=15000)
    check('T13_PATIENT_REHYDRATED',page.locator('#ci_signature_status').inner_text()=='Firma vinculada a esta versión')
    check('T21_DATE_STABLE',payload()['signature_document_date']==first_date)
    page.locator('#ci_review_confirm_informed').check()
    draw(page,'#ci_doctor_signature_canvas')
    page.wait_for_function("document.querySelector('#ci_doctor_signature_status').textContent.includes('vinculada')",timeout=15000)
    check('T07_REAL_DOCTOR',page.locator('#ci_doctor_signature_status').inner_text()=='Firma vinculada a esta versión')
    save(page)
    p=payload();check('T03_BOTH_SIGNATURES',p['signature_binding_status']=={'patient':'valid_bound_signature','doctor':'valid_bound_signature'})
    check('T12_DOCTOR_METADATA',p['signatures']['doctor']['binding']['version']==1)
    open_draft(page)
    page.wait_for_function("document.querySelector('#ci_doctor_signature_status').textContent.includes('vinculada')",timeout=15000)
    check('T13_DOCTOR_REHYDRATED',page.locator('#ci_doctor_signature_status').inner_text()=='Firma vinculada a esta versión')
    page.locator('#ci_signer_choice_other').check()
    check('T15_SIGNER_STALE',page.locator('#ci_signature_status').inner_text()=='Firma requiere confirmación nuevamente')
    page.locator('#ci_signer_choice_patient').check()
    page.locator('#ci_review_confirm_informed').check()
    page.locator('#ci_doctor_signature_clear').click()
    sig=page.evaluate("""() => { const c=document.createElement('canvas');c.width=220;c.height=90;const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,220,90);x.strokeStyle='#0f172a';x.lineWidth=3;x.beginPath();x.moveTo(20,25);x.lineTo(170,65);x.stroke();window.__testRegSig=c.toDataURL('image/png');window.mxmedPhysicianSignature={read:()=>window.__testRegSig,refresh:async()=>{}};document.dispatchEvent(new Event('mxmed:signature-changed'));return window.__testRegSig;}""")
    digest=hashlib.sha256(base64.b64decode(sig.split(',')[1])).hexdigest()
    subprocess.check_call(['mysql',DB,'-e',"CREATE TABLE physician_signatures (doctor_id VARCHAR(64) PRIMARY KEY, checksum_sha256 CHAR(64) NOT NULL)"])
    subprocess.check_call(['mysql',DB,'-e',f"INSERT INTO physician_signatures VALUES ('1','{digest}')"])
    check('T09_REGISTERED_NOT_AUTO',not page.locator('#ci_doctor_signature_source_registered').is_checked())
    page.locator('#ci_doctor_signature_apply_registered').click()
    page.wait_for_function("document.querySelector('#ci_doctor_signature_status').textContent.includes('vinculada')",timeout=15000)
    check('T10_REGISTERED_EXPLICIT',page.locator('#ci_doctor_signature_status').inner_text()=='Firma vinculada a esta versión')
    save(page)
    p=payload();check('T11_REGISTERED_OWNERSHIP',p['signature_binding_status']['doctor']=='valid_bound_signature' and p['signatures']['doctor']['source']=='registered_profile')
    open_draft(page)
    page.wait_for_function("document.querySelector('#ci_doctor_signature_status').textContent.includes('vinculada')",timeout=15000)
    check('T13_REGISTERED_REHYDRATED',page.locator('#ci_doctor_signature_status').inner_text()=='Firma vinculada a esta versión')
    page.locator('#ci_signatures_back').click()
    page.locator('#ci_review_edit_button').click()
    page.locator('#ci_review_edit_procedimiento').fill('Procedimiento materialmente cambiado')
    page.locator('#ci_review_apply').click()
    expect(page.locator('#ci_review_html')).to_contain_text('Procedimiento materialmente cambiado',timeout=15000)
    check('T25_PREVIEW', True)
    page.locator('#ci_save_as_template').click()
    expect(page.locator('#ci_save_template_overlay')).to_be_visible()
    page.locator('#ci_save_template_name').fill('Plantilla vinculacion QA')
    page.locator('#ci_save_template_confirm').click()
    expect(page.locator('#ci_save_template_overlay')).to_be_hidden()
    row=subprocess.check_output(['mysql','--raw','-N','-B',DB,'-e',"SELECT content_json FROM clinical_consent_templates WHERE template_name='Plantilla vinculacion QA'"],text=True)
    template=json.loads(row)
    check('T26_TEMPLATE',template['procedimiento']=='Procedimiento materialmente cambiado' and 'signatures' not in template and 'patient_snapshot' not in template)
    page.locator('#ci_review_continue').click()
    check('T14_CONTENT_STALE',page.locator('#ci_doctor_signature_status').inner_text()=='Firma requiere confirmación nuevamente')
    subprocess.check_call(['mysql',DB,'-e',"UPDATE clinical_documents SET payload_json=JSON_REMOVE(payload_json,'$.signatures.doctor.binding') WHERE document_type='consentimiento_informado' ORDER BY id DESC LIMIT 1"])
    reload_to_draft(page)
    page.wait_for_function("document.querySelector('#ci_doctor_signature_status').textContent.includes('vinculación sin verificar')",timeout=15000)
    check('T22_LEGACY_DRAFT_UI',page.locator('#ci_doctor_signature_status').inner_text()=='Firma anterior: vinculación sin verificar')
    subprocess.check_call(['mysql',DB,'-e',"UPDATE clinical_documents SET payload_json=JSON_SET(payload_json,'$.signatures.doctor.source','remote_qr') WHERE document_type='consentimiento_informado' ORDER BY id DESC LIMIT 1"])
    reload_to_draft(page)
    page.wait_for_function("document.querySelector('#ci_doctor_signature_status').textContent.includes('sin vinculación V1')",timeout=15000)
    check('T23_REMOTE_QR_UNBOUND_UI',page.locator('#ci_doctor_signature_status').inner_text()=='Firma remota sin vinculación V1')
    check('NO_PAGE_ERRORS',not errors)
    browser.close()
