"""Read-only FUNC-CAT02B QA on the actual Director runtime at port 18148."""
from playwright.sync_api import expect,sync_playwright

BASE='http://127.0.0.1:18148';SESSION='director-lon07c-review'
with sync_playwright() as playwright:
 browser=playwright.chromium.launch(headless=True)
 for width,height,sidebar in [(1440,900,'compact'),(1366,768,'compact'),(1366,768,'expanded'),(390,844,'mobile')]:
  context=browser.new_context(viewport={'width':width,'height':height})
  context.add_cookies([{'name':'PHPSESSID','value':SESSION,'url':BASE}])
  page=context.new_page();errors=[];writes=[];catalog=[]
  page.on('pageerror',lambda error:errors.append(str(error)))
  page.on('response',lambda response:catalog.append(response.status) if '/study-types?' in response.url else None)
  page.route('**/api/**',lambda route:route.continue_() if route.request.method in ('GET','HEAD','OPTIONS') else (writes.append(route.request.url),route.abort()))
  page.goto(BASE+'/index.html?review_patient=plan02ux&qa_tools=hide',wait_until='domcontentloaded')
  if sidebar=='expanded':page.evaluate('document.querySelector("#mmSidebar [data-action=sidebar-toggle]").click()')
  page.locator('[data-exp-tabs] [data-bs-target="#t-estudios"]').click()
  page.locator('.vis06-intent-card').first.click()
  page.wait_for_selector('[data-hier-node="functional"]',timeout=20000)
  page.locator('[data-hier-node="functional"]').click()
  page.locator('[data-hier-node="audiovestibular"]').click()
  page.locator('.ordcomp [data-tax03c-search]').fill('PEATC')
  expect(page.locator('.ordcomp [data-tax03c-key="evoked_auditory_baep"]')).to_be_visible(timeout=10000)
  page.get_by_role('button',name='Volver a ESTUDIOS FUNCIONALES').click()
  expect(page.locator('[data-hier-node="gi_motility"]')).to_be_visible()
  page.locator('[data-hier-node="gi_motility"]').click()
  expect(page.locator('.ordcomp [data-tax03c-key="esophageal_manometry"]')).to_be_visible()
  expect(page.locator('.ordcomp [data-tax03c-key="esophageal_ph_monitoring"]')).to_be_visible()
  assert page.locator('.ordcomp [data-ordcomp-featured],.ordcomp-full-catalog').count()==0
  page.locator('.ordcomp [data-tax03c-key="esophageal_manometry"]').click()
  if width==390:page.get_by_role('button',name='Ver órdenes').click()
  expect(page.locator('.functional-parameter-panel')).to_be_visible()
  assert page.locator('.functional-parameter-panel').get_attribute('aria-label')=='Parámetros funcionales del estudio'
  technique=page.locator('.functional-parameter-panel select[data-functional-field="gi_technique"]')
  technique.focus()
  assert technique.evaluate('(element)=>document.activeElement===element && element.labels.length===1 && element.labels[0].textContent.includes("Técnica")')
  assert 'Fisiología gastrointestinal (1)' in page.locator('.ordcomp-summary').inner_text()
  technique.select_option('HIGH_RESOLUTION')
  expect(page.locator('.functional-item-summary')).to_contain_text('Alta resolución')
  if width==390:page.get_by_role('button',name='Volver al catálogo').click()
  page.locator('.ordcomp [data-tax03c-key="esophageal_ph_monitoring"]').click()
  if width==390:page.get_by_role('button',name='Ver órdenes').click()
  panels=page.locator('.functional-parameter-panel')
  expect(panels).to_have_count(1)
  panels.locator('[data-functional-field="gi_technique"]').select_option('PH_IMPEDANCE')
  panels.locator('[data-functional-field="acid_suppression"]').select_option('ON_THERAPY')
  assert 'Fisiología gastrointestinal (2)' in page.locator('.ordcomp-summary').inner_text()
  assert page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'),(width,sidebar,page.evaluate('document.documentElement.scrollWidth'))
  if width in (1440,390):page.screenshot(path=f'/tmp/func-cat02b-live-{width}x{height}.png',full_page=True)
  if width==390:page.get_by_role('button',name='Volver al catálogo').click()
  page.locator('.ordcomp [data-tax03c-search]').fill('baep')
  expect(page.locator('.ordcomp [data-tax03c-key="evoked_auditory_baep"]')).to_be_visible(timeout=10000)
  page.locator('.ordcomp [data-tax03c-search]').fill('holter')
  expect(page.locator('.ordcomp [data-tax03c-key="holter"]')).to_be_visible(timeout=10000)
  page.locator('.ordcomp [data-tax03c-key="holter"]').click()
  if width==390:page.get_by_role('button',name='Ver órdenes').click()
  page.locator('.ordcomp [data-tax03c-functional]').last.click()
  expect(page.locator('.functional-parameter-panel [data-functional-field="duration"]')).to_be_visible()
  if width==390:page.get_by_role('button',name='Volver al catálogo').click()
  page.locator('.ordcomp [data-tax03c-search]').fill('echo')
  expect(page.locator('.ordcomp')).to_contain_text('Coincidencias en otras familias',timeout=10000)
  assert catalog and all(code==200 for code in catalog),catalog
  assert not errors and not writes,(errors,writes)
  print(f'QA_REAL_RUNTIME_{width}x{height}_{sidebar}=PASS',flush=True)
  context.close()
 browser.close()
