"""Read-only shell geometry/guard QA; session supplied locally, never committed."""
import os
from playwright.sync_api import sync_playwright,expect
with sync_playwright() as p:
 b=p.chromium.launch(headless=True)
 for w,h in [(1440,900),(1366,768),(390,844)]:
  page=b.new_page(viewport={'width':w,'height':h});page.context.add_cookies([{'name':'PHPSESSID','value':os.environ['ORD_COMP01_REVIEW_SESSION'],'domain':'127.0.0.1','path':'/'}])
  page.on('pageerror',lambda error:print('PAGEERROR',error,flush=True))
  page.route('**/api/**',lambda route:route.continue_() if route.request.method in ('GET','HEAD','OPTIONS') else route.abort())
  page.goto('http://127.0.0.1:18148/index.html?review_patient=plan02ux&qa_tools=hide',wait_until='domcontentloaded')
  page.locator('[data-exp-tabs] [data-bs-target="#t-estudios"]').click();page.locator('.vis06-intent-card').first.click()
  page.locator('[data-hier-node="laboratory"]').click();page.locator('[data-hier-node="urine"]').click()
  expect(page.locator('[data-ordcomp-featured] button')).to_have_count(6)
  expect(page.locator('[data-ordcomp-featured] button').first).to_be_visible()
  expect(page.locator('[data-catalog-group]')).to_have_count(7)
  labels=[node.get_attribute('data-catalog-group') for node in page.locator('[data-catalog-group]').all()]
  assert labels.index('Semen')==labels.index('Microbiología urinaria')+1
  expect(page.locator('.ordcomp [data-tax03c-status]')).to_contain_text('26 estudios disponibles')
  for name in ('Creatinina en orina (muestra aislada)','Sodio en orina (muestra aislada)','Potasio en orina (muestra aislada)','Prueba de embarazo en orina (cualitativa)','Glucosa en líquido cefalorraquídeo (LCR)','Proteínas totales en líquido cefalorraquídeo (LCR)','Control de semen posvasectomía'):
   assert page.locator('[data-catalog-group] [data-tax03c-id]').filter(has_text=name).count()==1
  expect(page.locator('.ordcomp-custom-link')).to_be_hidden()
  page.locator('.ordcomp-full-catalog > summary').click()
  expect(page.locator('.ordcomp-custom-link')).to_be_visible()
  page.locator('.ordcomp-full-catalog > summary').click()
  expect(page.locator('.ordcomp-custom-link')).to_be_hidden()
  page.locator('[data-ordcomp-featured] button').first.click()
  assert page.locator('.specimen-editor').count()==0
  page.locator('.ordcomp [data-tax03c-search]').fill('Glucosa en líquido corporal')
  page.locator('.ordcomp [data-tax03c-results] [data-tax03c-id]').filter(has_text='Glucosa en líquido corporal').first.click()
  if w<768:page.get_by_role('button',name='Ver órdenes',exact=True).click()
  expect(page.locator('.specimen-editor select')).to_have_count(1)
  page.locator('.specimen-editor select').select_option('PLEURAL_FLUID')
  expect(page.locator('.ordcomp-summary .tax03c-selected-row').filter(has_text='Glucosa en líquido corporal')).to_contain_text('Líquido pleural')
  assert page.locator('.ordcomp-summary .tax03c-selected-row strong').first.evaluate('(e)=>Number(getComputedStyle(e).fontWeight)>=700')
  for state in (['compact','expanded'] if w>768 else ['mobile']):
   if state=='expanded':page.evaluate("document.querySelector('#mmSidebar [data-action=sidebar-toggle]').click()")
   page.wait_for_timeout(350)
   geometry=page.evaluate("(()=>{const tabs=document.querySelector('[data-exp-tabs]'),target=tabs.querySelector('[data-bs-target=\"#t-estudios\"]'),tr=tabs.getBoundingClientRect(),r=target.getBoundingClientRect();return {width:innerWidth,scroll:document.documentElement.scrollWidth,tabScroll:tabs.scrollWidth,tabClient:tabs.clientWidth,tabText:target.innerText,tabRect:r.toJSON(),tabFits:r.left>=tr.left&&r.right<=tr.right,columns:getComputedStyle(document.querySelector('.ordcomp-workspace')).gridTemplateColumns,summary:document.querySelector('.ordcomp-summary').getBoundingClientRect().toJSON()}})()")
   print(w,state,geometry,flush=True)
   assert 'Estudios de diagnóstico' in geometry['tabText'] and geometry['tabFits']
   if w>768:assert geometry['tabScroll']<=geometry['tabClient']
   expect(page.locator('.ordcomp-review-one')).to_have_count(1)
   page.get_by_role('button',name='+ Agregar estudios',exact=True).click()
   expect(page.locator('.ordcomp-add-chooser')).to_be_visible()
   assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
   page.locator('.ordcomp').scroll_into_view_if_needed();page.screenshot(path=f'/tmp/ordcomp01_live_{w}_{state}.png',full_page=True)
   page.get_by_role('button',name='Cerrar',exact=True).click()
   page.locator('.ordcomp-review-one').scroll_into_view_if_needed()
   page.wait_for_timeout(450)
   scroll_before=page.evaluate('scrollY')
   page.locator('.ordcomp-review-one').click()
   expect(page.locator('dialog.ordcomp-review[open]')).to_be_visible()
   assert page.evaluate('document.activeElement.closest("dialog.ordcomp-review")!==null')
   expect(page.locator('dialog.ordcomp-review .ordcomp-priority input[type=radio]')).to_have_count(2)
   page.locator('dialog.ordcomp-review .ordcomp-priority input[value="Urgente"]').check()
   page.screenshot(path=f'/tmp/ordcomp02_r1_modal_{w}_{state}.png')
   page.get_by_role('button',name='Cerrar revisión').click()
   expect(page.locator('.ordcomp-review-one')).to_be_focused()
   page.locator('.ordcomp-review-one').click()
   expect(page.locator('dialog.ordcomp-review .ordcomp-priority input[value="Urgente"]')).to_be_checked()
   page.get_by_role('button',name='Cerrar revisión').click()
   page.wait_for_timeout(300)
   scroll_after=page.evaluate('scrollY')
   print('REVIEW_SCROLL',w,state,scroll_before,scroll_after,flush=True)
   assert abs(scroll_after-scroll_before)<=(24 if w<768 else 1)
   assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
  page.locator('[data-exp-tabs] [data-bs-target="#t-resumen-longitudinal"]').click()
  expect(page.locator('.mx-patient-leave-dialog[open]')).to_be_visible()
  page.locator('.mx-patient-leave-dialog [data-stay]').click()
  expect(page.locator('.ordcomp')).to_be_visible()
  page.close()
 b.close()
