# Disposable Director fixture only: see PLAN02B_REVIEW.md.
from playwright.sync_api import sync_playwright,expect
from pathlib import Path
import os
import json,subprocess
out=Path(os.environ['PLAN02B_ARTIFACTS']);base='http://127.0.0.1:18143';full=json.loads((out/'full-results.json').read_text());writes=full['writes'];aid=writes[2]['body']['data']['appointment_id'];tid=writes[3]['body']['data']['item']['task_id'];report={}
with sync_playwright() as p:
 b=p.chromium.launch(headless=True);page=b.new_page(viewport={'width':1440,'height':900},timezone_id='America/Mexico_City');page.set_default_timeout(22000);page.goto(base+'/index.html?review_patient=plan02&review_encounter=open&qa_tools=hide',wait_until='commit');page.wait_for_function('document.querySelector("#m7-workspace [data-m7-body]")?.dataset.encounterId==="1015"',timeout=55000);page.wait_for_timeout(1200)
 docs=page.request.get(base+'/api/clinical/index.php/doctors/1/patients/p_plan02_review/documents?limit=200').json()['data']['items'];ids=[r['body']['data']['document_uuid'] for r in writes[:2]];assert all(any(d['document_uuid']==x and str(d['encounter_ref_id'])=='1015' for d in docs) for x in ids)
 appt=page.request.get(base+'/api/agenda/index.php/appointments/'+aid).json()['data'];assert appt['patient_id']=='p_plan02_review' and appt['doctor_id']=='1' and appt['status']=='tentative';task=page.request.get(base+'/api/clinical/index.php/patients/p_plan02_review/longitudinal/tasks/'+str(tid)).json()['data']['item'];assert task['state']=='OPEN' and task['due_at'] is None and task['appointment_id']==aid and task['source_encounter_id']==1015
 report.update(orders=ids,appointment=appt,task=task)
 page.evaluate("[...document.querySelectorAll('.vis07-admin button')].find(e=>e.textContent==='Ir a Agenda').click()");page.get_by_role('button',name='Salir y mantener consulta en curso',exact=True).click();page.wait_for_timeout(1500);page.locator('[data-ag-view-mode="day"]').click();page.locator('[data-day-mini-nav="next"]').click();page.locator('[data-day-mini-date="2026-10-05"]').click();card=page.locator('.mx-ag-custom-day-root .is-occupied[data-event-id="'+aid+'"]');expect(card).to_contain_text('1 seguimiento pendiente');expect(card).to_contain_text(task['title']);assert page.locator('.is-available [data-plan02b-linked],.is-blocked [data-plan02b-linked]').count()==0;card.scroll_into_view_if_needed();page.screenshot(path=str(out/'agenda-card.png'))
 expect(page.locator('[data-agf01-group="no_due"] h6')).to_have_text('Sin fecha límite');expect(page.locator('[data-agf01-group="no_due"]')).to_contain_text(task['title']);assert page.locator('[data-alr01-badge]').inner_text()=='2';report['attention_badge']='2';page.locator('[data-agf01-group="no_due"]').scroll_into_view_if_needed();page.screenshot(path=str(out/'agenda-followups.png'))
 # Reference also survives Week rendering and does not occupy an available card.
 page.locator('[data-ag-view-mode="week"]').click();page.wait_for_timeout(1200);assert page.locator('.is-available [data-plan02b-linked],.is-blocked [data-plan02b-linked]').count()==0;report['week_reference_count']=page.locator('.mx-ag-custom-week-root [data-plan02b-linked]').count()
 report['encounters']=subprocess.check_output(['mysql','--batch','--skip-column-names','mxmed_director_review_lon07c','-e',"SELECT encounter_id,status,COALESCE(appointment_id,'NULL') FROM clinical_encounters WHERE patient_id='p_plan02_review'"],text=True).strip();assert report['encounters']=='1015\topen\tNULL'
 slots=page.request.get(base+'/api/agenda/index.php/availability?doctor_id=1&consultorio_id=1&date=2026-09-28').json()['data']['slots'];assert len(slots)==6;report['baseline']=slots
 (out/'agenda-results.json').write_text(json.dumps(report,indent=2,ensure_ascii=False));print('PASS canonical full readback, real appointment card reference, no available/blocked reference, badge2, baseline6, encounter1015 OPEN',flush=True);b.close()
