import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const context={window:{}};
vm.runInNewContext(await readFile(new URL('../../../assets/js/core/dirty-tracker.js',import.meta.url),'utf8'),context);
let state={name:'Original',theme:null,nested:{second:true,given:'Nombre'}};
const tracker=context.window.mxmedCreateDirtyTracker({readState:()=>state});
assert.equal(tracker.isDirty(),false);
tracker.captureBaseline();
state.name='Edición';assert.equal(tracker.isDirty(),true);
state.name='Original';assert.equal(tracker.isDirty(),false);
state.nested.second=false;assert.equal(tracker.isDirty(),true);
state.nested.second=true;assert.equal(tracker.isDirty(),false);
state.theme='mxmed_teal';assert.equal(tracker.isDirty(),true,'canonical null is distinct from an explicitly stored key');
tracker.captureBaseline();assert.equal(tracker.isDirty(),false);
state={theme:'mxmed_teal',nested:{given:'Nombre',second:true},name:'Original'};
assert.equal(tracker.isDirty(),false,'property insertion order does not affect baseline');
state.nested.given='Otro';assert.equal(tracker.isDirty(),true,'baseline is a deep independent snapshot');
console.log('DIRTY_TRACKER=PASS');
