import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const app = readFileSync(new URL('../../assets/js/app.js', import.meta.url), 'utf8');
const html = readFileSync(new URL('../../index.html', import.meta.url), 'utf8');
const shell = readFileSync(new URL('../../assets/js/clinical/m7-workspace.js', import.meta.url), 'utf8');
const endpoint = readFileSync(new URL('../../api/clinical/index.php', import.meta.url), 'utf8');
const from = app.indexOf('const ensureActiveEncounter =');
const to = app.indexOf('const openArchivePatientRecord =', from);
assert.ok(from > 0 && to > from);
assert.doesNotMatch(app.slice(from, to), /method\s*:\s*['"]POST['"]/);
assert.doesNotMatch(app.slice(to, to + 6000), /ensureActiveEncounter\s*\(/);
assert.equal((app.match(/window\.mxmedExplicitStartEncounter\s*=/g) || []).length, 1);
assert.match(app, /'Idempotency-Key':key/);
assert.match(app, /if\(snapshot\.encounter\) return snapshot\.encounter/);
assert.match(html, /data-m7-start>Iniciar consulta/);
assert.match(html, /window\.mxmedExplicitStartEncounter\(safePatientId\)/);
assert.doesNotMatch(shell, /fetch\([^\n]*method\s*:\s*['"]POST['"]/);
assert.match(shell, /snapshot\.meta\.integrity_v1 !== true/);
assert.match(shell, /\['closed','voided'\]/);
assert.match(shell, /show\(legacyPanel, false\)/);
assert.equal((html.match(/data-m7-section=/g) || []).length, 7);
assert.doesNotMatch(html.slice(html.indexOf('id="m7-workspace"'), html.indexOf('id="mm-p10-bar"')), /<(input|textarea|select)\b/i);
assert.match(endpoint, /clinical_m6_patient_route_uses_v1\(\$context, \$patientId\)/);
console.log('M7 WS01 static boundary: PASS');
