<?php
declare(strict_types=1);
$c=__DIR__.'/../contracts/';$s=__DIR__.'/../services/';
require_once $c.'CanonicalAuditEventType.php';require_once $c.'TrustedAuditContext.php';
foreach(['ContextIdPolicy','RequestIdProvider','CorrelationIdProvider','TrustedContinuationSource','TrustedCorrelationReference','TrustedRequestContext','TrustedActorContext','ExternalCorrelationEnvelope'] as $n)require_once $c.$n.'.php';
foreach(['UuidV4ContextIdPolicy','UuidV4Generator','RandomRequestIdProvider','RandomCorrelationIdProvider','CorrelatableOperationCatalog','SourceModuleCatalog','CanonicalSourceRoutePolicy','TrustedCorrelationContinuationResolver','NestedCorrelationPolicy','NonHttpBatchCorrelationPlanner','RequestContextFactory','ActorContextFactory','RequestScopedContextAccessor','ContextPropagator','SystemActorContextFactory','AuditWriterContextBridge'] as $n)require_once $s.$n.'.php';
use Platform\Contracts\{CorrelationIdProvider,RequestIdProvider,TrustedContinuationSource,TrustedRequestContext};
use Platform\Services\{ActorContextFactory,AuditWriterContextBridge,CanonicalSourceRoutePolicy,ContextPropagator,CorrelatableOperationCatalog,NestedCorrelationPolicy,NonHttpBatchCorrelationPlanner,RandomCorrelationIdProvider,RandomRequestIdProvider,RequestContextFactory,RequestScopedContextAccessor,SourceModuleCatalog,SystemActorContextFactory,TrustedCorrelationContinuationResolver,UuidV4ContextIdPolicy,UuidV4Generator};
$u=0;$up=0;$n=0;$np=0;function ok(bool $v,string $x):void{global $u,$up;$u++;if(!$v)throw new RuntimeException('unit:'.$x);$up++;}function no(callable $f,string $x):void{global $n,$np;$n++;try{$f();}catch(Throwable){$np++;return;}throw new RuntimeException('negative:'.$x);}
final class FakeReq implements RequestIdProvider{public int $i=0;private array $v=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','33333333-3333-4333-8333-333333333333','44444444-4444-4444-8444-444444444444','55555555-5555-4555-8555-555555555555','66666666-6666-4666-8666-666666666666','77777777-7777-4777-8777-777777777777','88888888-8888-4888-8888-888888888888','99999999-9999-4999-8999-999999999999'];public function serverGeneratedRequestId():string{return $this->v[$this->i++];}}
final class FakeCorr implements CorrelationIdProvider{public int $i=0;private array $v=['aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','cccccccc-cccc-4ccc-8ccc-cccccccccccc','dddddddd-dddd-4ddd-8ddd-dddddddddddd','eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','ffffffff-ffff-4fff-8fff-ffffffffffff'];public function serverGeneratedCorrelationId(string $o):string{return $this->v[$this->i++];}}
final class FakeSource implements TrustedContinuationSource{public function resolveTrustedOperation(string $r):?array{if($r==='trusted-login')return ['correlation_id'=>'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','operation_type'=>'AUTH_LOGIN','provenance'=>'db:login'];if($r==='uncatalogued')return ['correlation_id'=>'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','operation_type'=>'NOT_RATIFIED','provenance'=>'db:x'];return null;}}
$ids=new UuidV4ContextIdPolicy();$ops=new CorrelatableOperationCatalog();$mods=new SourceModuleCatalog();$routes=new CanonicalSourceRoutePolicy(['/auth/login','/profile/{profile_id}/claim','/webhooks/stripe'],['subscription-expiration-scan'],['audit-verify'],['activate-after-payment']);$rq=new FakeReq();$cq=new FakeCorr();$factory=new RequestContextFactory($rq,$cq,$ids,$ops,$mods,$routes);$resolver=new TrustedCorrelationContinuationResolver(new FakeSource(),$ids,$ops);
$realReq=(new RandomRequestIdProvider(new UuidV4Generator()))->serverGeneratedRequestId();$realCorr=(new RandomCorrelationIdProvider(new UuidV4Generator()))->serverGeneratedCorrelationId('AUTH_LOGIN');ok(preg_match(UuidV4ContextIdPolicy::PATTERN,$realReq)===1,'uuid_request_generation');ok(preg_match(UuidV4ContextIdPolicy::PATTERN,$realCorr)===1,'uuid_correlation_generation');ok(strlen($realReq)===36&&strtolower($realReq)===$realReq,'lowercase_length');
$a=$factory->newHttp([],[],[],'AUTH_LOGIN','session-1','AUTH','POST','/auth/login','192.0.2.1','Browser');ok((new ReflectionClass(TrustedRequestContext::class))->isReadOnly(),'request_immutable');ok($a->requestId!==$a->correlationId,'request_not_correlation');ok(count($ops->all())===13,'operation_count');ok(count($ops->eventMap())===28,'event_operation_rows');ok(array_keys($ops->eventMap())===Platform\Contracts\CanonicalAuditEventType::all(),'event_operation_complete');ok($ops->operationForEvent('AUTH_LOGIN_FAILED')==='AUTH_LOGIN','event_operation_mapping');ok(count($mods->all())===9,'source_module_count');ok(count($mods->eventMap())===28,'event_module_rows');ok(array_keys($mods->eventMap())===Platform\Contracts\CanonicalAuditEventType::all(),'event_module_complete');ok($mods->moduleForEvent('BREAK_GLASS_STARTED')==='SECURITY','event_module_mapping');ok($a->sourceRoute==='POST /auth/login','http_source_route');
$ref=$resolver->resolve('trusted-login');$b=$factory->continueHttp([],[],[],'AUTH_LOGIN',$ref,null,'AUTH','POST','/auth/login',null,null);ok($a->correlationId===$b->correlationId&&$a->requestId!==$b->requestId,'multiple_requests_one_correlation');$nestedPolicy=new NestedCorrelationPolicy($ids,$ops);$inherited=$nestedPolicy->inheritSameLogicalOperation($a,'AUTH_LOGIN');$nested=$factory->continueHttp([],[],[],'AUTH_LOGIN',$inherited,null,'AUTH','POST','/auth/login',null,null);$nestedPolicy->assertSameOperationCorrelation($a,$nested);ok($nested->correlationId===$a->correlationId,'nested_inherits');$independent=$factory->newHttp([],[],[],'PROFILE_CLAIM',null,'PROFILE','POST','/profile/{profile_id}/claim',null,null);$nestedPolicy->assertIndependentCorrelation($a,$independent);ok($independent->correlationId!==$a->correlationId,'independent_new_correlation');
$job=$factory->nonHttp('JOB','subscription-expiration-scan','AUTH_SESSION_LIFECYCLE',null,null,'SYSTEM');$job2=$factory->nonHttp('JOB','subscription-expiration-scan','AUTH_SESSION_LIFECYCLE',null,null,'SYSTEM');ok($job->sourceRoute==='JOB:subscription-expiration-scan','job_route');ok($job->requestId!==$job2->requestId,'new_job_request_id');$batch=new NonHttpBatchCorrelationPlanner();$batch->assertExecutionAlias($job,$job->requestId);$batch->assertSeparateExecutions($job,$job2);$batch->assertIndependentBusinessUnits([$job,$job2]);ok($job->executionId()===$job->requestId,'execution_alias');ok($ref->serverLookupProvenance==='db:login','trusted_continuation');
$actors=new ActorContextFactory();$actor=$actors->fromBackend(['authenticated_identity_id'=>'operator-1','real_actor_type'=>'OPERATOR','real_actor_id'=>'operator-1','effective_entity_type'=>'DOCTOR','effective_entity_id'=>'doctor-opaque','actor_role'=>'SUPPORT','actor_scope'=>'doctor:opaque','ownership_relation'=>'DELEGATED','delegation'=>true,'reason'=>'approved','target_type'=>'PROFILE','target_id'=>'opaque','authorization_provenance'=>'grant']);ok($actor->realActorId!==$actor->effectiveEntityId,'real_effective');$audit=(new AuditWriterContextBridge())->toAuditContext($a,$actor);ok($audit->requestId===$a->requestId&&$audit->correlationId===$a->correlationId,'writer_handoff');$access1=new RequestScopedContextAccessor();$access2=new RequestScopedContextAccessor();$access1->setOnce($a);$access2->setOnce($b);ok($access1->get()!==$access2->get(),'request_isolation');ok((new ContextPropagator())->forFailure($a)===$a,'failure_propagation');ok((new SystemActorContextFactory())->create('job','JOB','opaque','scheduler')->auditActorType()==='SYSTEM','system_actor');ok(CorrelatableOperationCatalog::CHILD_CORRELATIONS_SUPPORTED===false,'no_child_correlations');ok(!property_exists(TrustedRequestContext::class,'executionId'),'no_persisted_execution_id');ok($factory->newHttp([],[],[],'UNLISTED_NEW_OPERATION',null,'SYSTEM','POST','/auth/login',null,null)->operationKey==='UNLISTED_NEW_OPERATION','uncatalogued_can_start');
no(fn()=>$ids->assertRequestId('AAAAAAAA-AAAA-4AAA-8AAA-AAAAAAAAAAAA'),'uppercase_uuid');no(fn()=>$ids->assertRequestId('11111111-1111-1111-8111-111111111111'),'uuid_v1');no(fn()=>$ids->assertRequestId('11111111-1111-3111-8111-111111111111'),'uuid_v3');no(fn()=>$ids->assertRequestId('11111111-1111-5111-8111-111111111111'),'uuid_v5');no(fn()=>$ids->assertRequestId('11111111111141118111111111111111'),'no_hyphens');no(fn()=>$ids->assertRequestId('invalid'),'invalid_uuid');no(fn()=>$ids->assertRequestId(str_repeat('a',37)),'oversized');no(fn()=>$factory->newHttp(['request_id'=>$realReq],[],[],'AUTH_LOGIN',null,'AUTH','POST','/auth/login',null,null),'body_request');no(fn()=>$factory->newHttp([],['request_id'=>$realReq],[],'AUTH_LOGIN',null,'AUTH','POST','/auth/login',null,null),'query_request');no(fn()=>$factory->newHttp([],[],['X-Request-ID'=>$realReq],'AUTH_LOGIN',null,'AUTH','POST','/auth/login',null,null),'header_request');no(function()use($a){$a->requestId='x';},'request_mutation');no(fn()=>$ids->assertRequestId('patient-990104-derived'),'pii_like_request');
no(fn()=>Platform\Contracts\TrustedRequestContext::fromTrustedBoundary($realReq,$realReq,'AUTH_LOGIN',null,'AUTH','POST /auth/login',null,null,'HTTP','server',$ids),'request_corr_alias');no(fn()=>$resolver->resolve($realCorr),'valid_but_untrusted_continuation');no(fn()=>$resolver->resolve('uncatalogued'),'uncatalogued_continuation');no(fn()=>$factory->webhook(['correlation_id'=>'pi_1'],[],[],'AUTH_LOGIN',null,'AUTH','POST','/webhooks/stripe',null,null),'provider_as_correlation');no(fn()=>$factory->webhook([],[],['X-Correlation-ID'=>$realCorr],'AUTH_LOGIN',null,'AUTH','POST','/webhooks/stripe',null,null),'arbitrary_webhook');
no(fn()=>$nestedPolicy->childCorrelation($a),'caller_child');$different=$factory->newHttp([],[],[],'AUTH_LOGIN',null,'AUTH','POST','/auth/login',null,null);no(fn()=>$nestedPolicy->assertSameOperationCorrelation($a,$different),'same_nested_new_corr');no(fn()=>$nestedPolicy->assertIndependentCorrelation($a,$nested),'independent_inherits');
foreach(['UNKNOWN','Platform\\Identity','modules/platform','AGENDA','PAYMENTS','CLINICAL'] as $bad)no(fn()=>$mods->assertKnown($bad),'bad_module_'.$bad);no(fn()=>$factory->newHttp(['source_module'=>'AUTH'],[],[],'AUTH_LOGIN',null,'AUTH','POST','/auth/login',null,null),'client_module');
no(fn()=>$routes->http('GET','/auth/login?x=1'),'query_route');no(fn()=>$routes->http('GET','example.test/auth/login'),'host_route');no(fn()=>$routes->http('GET','https://example.test/auth/login'),'scheme_route');no(fn()=>$routes->http('POST','/profile/990104/claim'),'concrete_route');no(fn()=>$routes->http('post','/auth/login'),'lower_method');no(fn()=>$routes->nonHttp('JOB','free-form'),'free_job');no(fn()=>$routes->nonHttp('CLI','audit-verify --all'),'cli_args');no(fn()=>$routes->nonHttp('JOB','secret=abc'),'secret_route');no(fn()=>$factory->newHttp(['source_route'=>'POST /auth/login'],[],[],'AUTH_LOGIN',null,'AUTH','POST','/auth/login',null,null),'client_route');
no(fn()=>Platform\Contracts\TrustedRequestContext::fromTrustedBoundary(requestId:$realReq,correlationId:$realCorr,operationKey:'AUTH_LOGIN',sessionId:null,sourceModule:'AUTH',sourceRoute:'POST /auth/login',trustedClientIp:null,trustedRawUserAgent:null,boundary:'HTTP',provenance:'server',policy:$ids,executionId:'extra'),'second_execution_field');no(fn()=>$batch->assertExecutionAlias($job,'00000000-0000-4000-8000-000000000000'),'execution_alias_mismatch');no(fn()=>$batch->assertSeparateExecutions($job,$job),'reuse_job_request');no(fn()=>$batch->assertIndependentBusinessUnits([$job,$job]),'batch_one_correlation');
$actorBase=['authenticated_identity_id'=>'u','real_actor_type'=>'USER','real_actor_id'=>'u','actor_role'=>'USER','actor_scope'=>'SELF','target_type'=>'ACCOUNT','target_id'=>'u','authorization_provenance'=>'session'];no(fn()=>$actors->fromBackend($actorBase,['actor_id'=>'evil']),'actor_body');no(fn()=>$actors->fromBackend($actorBase,[],['actor_role'=>'evil']),'actor_query');no(fn()=>$actors->fromBackend($actorBase,[],[],['X-Actor-Id'=>'evil']),'actor_header');no(fn()=>Platform\Contracts\TrustedActorContext::fromTrustedBackend(['actor_role'=>'UNKNOWN','actor_scope'=>'X','target_type'=>'X','target_id'=>'x','authorization_provenance'=>'x','trust_source'=>'backend_trusted']),'unknown_normal_actor');no(fn()=>Platform\Contracts\TrustedActorContext::fromTrustedBackend($actorBase+['break_glass'=>true,'trust_source'=>'backend_trusted']),'breakglass_reason');no(fn()=>Platform\Contracts\TrustedActorContext::fromTrustedBackend(['effective_entity_type'=>'USER','effective_entity_id'=>'x','actor_role'=>'X','actor_scope'=>'X','impersonation'=>true,'reason'=>'x','target_type'=>'X','target_id'=>'x','authorization_provenance'=>'x','trust_source'=>'backend_trusted']),'impersonation_real');
echo "UNIT_TESTS_TOTAL=$u\nUNIT_TESTS_PASS=$up/$u\nUNIT_TESTS_FAIL=".($u-$up)."\nNEGATIVES_TOTAL=$n\nNEGATIVES_BLOCKED=$np/$n\n";
