<?php
declare(strict_types=1);
foreach(glob(__DIR__.'/../contracts/*.php') as $f)require_once $f;foreach(glob(__DIR__.'/../repositories/*.php') as $f)require_once $f;foreach(glob(__DIR__.'/../services/*.php') as $f)require_once $f;
use Platform\Contracts\{AuditIpHasher,AuditSecretProvider,AuditUserAgentSummarizer,AuditUtcClock,AuditUuidProvider,CanonicalAuditEventInput,TrustedAuditContext};
use Platform\Repositories\CanonicalAuditTransactionPort;
use Platform\Services\{AuditV1PhysicalMapper,CanonicalAuditMetadataSanitizer,CanonicalAuditPolicyRegistry,CanonicalAuditSealer,CanonicalAuditSerializer,CanonicalAuditWriter,CoarseAuditUserAgentSummarizer,HmacSha256AuditIpHasher,TrustedAuditContextValidator};
$total=0;$pass=0;function ok(bool $v,string $n):void{global $total,$pass;$total++;if(!$v)throw new RuntimeException($n);$pass++;}function rejects(callable $f):bool{try{$f();}catch(Throwable){return true;}return false;}
$root=dirname(__DIR__,3);$policy=['rows'=>CanonicalAuditPolicyRegistry::canonicalRows()];
final class FixedUuidD11 implements AuditUuidProvider{public int $calls=0;public function generateCanonicalUuid():string{$this->calls++;return '018f2f3a-7b1c-7abc-8def-0123456789ab';}}
final class FixedClockD11 implements AuditUtcClock{public int $calls=0;private array $v=['2026-08-13T23:10:00.000000Z','2026-08-13T23:10:00.100000Z'];public function nowUtc():string{return $this->v[$this->calls++];}}
final class FixedSecretD11 implements AuditSecretProvider{public function currentAuditIpKey():array{return ['version'=>'audit-ip-v7','secret'=>str_repeat('k',32)];}}
final class SpyIpD11 implements AuditIpHasher{public int $calls=0;public function __construct(private AuditIpHasher $inner){}public function hashTrustedNetworkAddress(string $v):array{$this->calls++;return $this->inner->hashTrustedNetworkAddress($v);}}
final class SpyUaD11 implements AuditUserAgentSummarizer{public int $calls=0;public function __construct(private AuditUserAgentSummarizer $inner){}public function summarizeTrustedUserAgent(string $v):string{$this->calls++;return $this->inner->summarizeTrustedUserAgent($v);}}
final class FakeTxD11 implements CanonicalAuditTransactionPort{
 public array $calls=[];public array $row=[];public array $headUpdate=[];public bool $failInsert=false;public bool $failUpdate=false;public bool $failLegacy=false;
 public array $head=['last_sequence_number'=>4,'last_event_hash'=>'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','hash_version'=>'sha256-hex-v1','updated_at'=>'2026-08-13T23:09:59.000000Z'];
 public function begin():void{$this->calls[]='BEGIN';}public function ensureHead(string $s,string $g,string $v):void{$this->calls[]='ENSURE_HEAD';}
 public function lockHead(string $s):array{$this->calls[]='SELECT_HEAD_FOR_UPDATE';return $this->head;}
 public function assertLegacyHeadMatchesLatest(string $s,int $q,string $h):void{$this->calls[]='VERIFY_LEGACY_HEAD';if($this->failLegacy)throw new RuntimeException('legacy_head_not_latest_event');}
 public function insertEvent(array $r):int{$this->calls[]='INSERT_EVENT';$this->row=$r;return $this->failInsert?0:1;}
 public function updateHead(string $s,int $eq,string $eh,?string $ev,?string $et,int $nq,string $nh,string $nv,string $nt):int{$this->calls[]='UPDATE_HEAD';$this->headUpdate=func_get_args();return $this->failUpdate?0:1;}
 public function commit():void{$this->calls[]='COMMIT';}public function rollBack():void{$this->calls[]='ROLLBACK';}
}
function makeWriterD11(array $policy,FakeTxD11 $tx,?FixedUuidD11 &$uuid=null,?FixedClockD11 &$clock=null,?SpyIpD11 &$ip=null,?SpyUaD11 &$ua=null):CanonicalAuditWriter{$uuid=new FixedUuidD11();$clock=new FixedClockD11();$ip=new SpyIpD11(new HmacSha256AuditIpHasher(new FixedSecretD11()));$ua=new SpyUaD11(new CoarseAuditUserAgentSummarizer());return new CanonicalAuditWriter(CanonicalAuditPolicyRegistry::canonical(),new CanonicalAuditMetadataSanitizer(),new TrustedAuditContextValidator(),$uuid,$clock,$ip,$ua,$tx,new CanonicalAuditSealer(new CanonicalAuditSerializer()),new AuditV1PhysicalMapper());}
$canonicalRegistry=CanonicalAuditPolicyRegistry::canonical();$canonicalRows=CanonicalAuditPolicyRegistry::canonicalRows();ok($canonicalRegistry->count()===28,'f07_policy_count');ok(count($canonicalRows)===28,'f07_policy_rows');ok(hash('sha256',json_encode($canonicalRows,JSON_UNESCAPED_SLASHES))==='a1617e960dbae4e0affe105bba2d33398f4690cb94f7af95fad8956246433307','f07_policy_semantic_hash');ok($canonicalRegistry->policyFor('AUTH_LOGIN_SUCCEEDED')['severity']==='INFO','f07_known_policy');ok(rejects(fn()=>$canonicalRegistry->policyFor('UNKNOWN_EVENT')),'f07_unknown_rejected');ok($canonicalRegistry->assertAllowed('AUTH_LOGIN_SUCCEEDED','SUCCESS','USER_REQUEST')['retention_class']==='AUTH_SECURITY','f07_pair_allowed');ok(rejects(fn()=>$canonicalRegistry->assertAllowed('AUTH_LOGIN_SUCCEEDED','FAILURE','USER_REQUEST')),'f07_pair_rejected');$mutated=$canonicalRows;$mutated[0]['severity']='CRITICAL';ok(CanonicalAuditPolicyRegistry::canonical()->policyFor($canonicalRows[0]['event_type'])['severity']===$canonicalRows[0]['severity'],'f07_registry_immutable');
$input=new CanonicalAuditEventInput('AUTH_LOGIN_SUCCEEDED','SUCCESS','USER_REQUEST',null,null,'IDENTITY','identity-42',[]);$context=TrustedAuditContext::fromServer('identity-42','USER','PATIENT','SELF','request-9','correlation-3','session-7','192.0.2.1','Mozilla/5.0 Chrome Macintosh','Identity','/login');
$tx=new FakeTxD11();$writer=makeWriterD11($policy,$tx,$uuid,$clock,$ip,$ua);$sealed=$writer->append($input,$context);
ok($uuid->calls===1,'uuid_provider_used');ok($clock->calls===2,'utc_clock_used');ok($ip->calls===1,'hmac_used');ok($ua->calls===1,'ua_used');ok($sealed->value('event_id')==='018f2f3a-7b1c-7abc-8def-0123456789ab','server_uuid');ok($sealed->value('sequence_number')===5,'sequence_from_head');ok($sealed->value('previous_hash')===str_repeat('a',64),'previous_hash_from_head');ok(preg_match('/^[a-f0-9]{64}$/',$sealed->value('event_hash'))===1,'sealed_hash');
ok($tx->calls===['BEGIN','ENSURE_HEAD','SELECT_HEAD_FOR_UPDATE','INSERT_EVENT','UPDATE_HEAD','COMMIT'],'versioned_transaction_order');ok($tx->headUpdate[3]==='sha256-hex-v1'&&$tx->headUpdate[7]==='sha256-hex-v1','known_version_preserved');ok($tx->headUpdate[8]==='2026-08-13T23:10:00.100000Z','updated_at_new_event');
$stored=json_decode($tx->row['metadata_json'],true,512,JSON_THROW_ON_ERROR);ok($stored['_audit_v1']['ip_hmac_key_version']==='audit-ip-v7','hmac_key_version');ok(!str_contains($tx->row['metadata_json'],'192.0.2.1'),'raw_ip_absent');ok(!str_contains($tx->row['metadata_json'],'Mozilla'),'raw_ua_absent');
$legacy=new FakeTxD11();$legacy->head=['last_sequence_number'=>7,'last_event_hash'=>str_repeat('b',64),'hash_version'=>null,'updated_at'=>'2026-08-13T23:00:00.000000Z'];$legacyWriter=makeWriterD11($policy,$legacy);$legacyEvent=$legacyWriter->append($input,$context);ok($legacy->calls===['BEGIN','ENSURE_HEAD','SELECT_HEAD_FOR_UPDATE','VERIFY_LEGACY_HEAD','INSERT_EVENT','UPDATE_HEAD','COMMIT'],'legacy_bridge_order');ok($legacyEvent->value('previous_hash')===str_repeat('b',64),'legacy_previous_hash_preserved');ok($legacy->headUpdate[3]===null&&$legacy->headUpdate[7]==='sha256-hex-v1','null_to_version_transition');ok($legacy->headUpdate[5]===8,'legacy_next_sequence');
$badLegacy=new FakeTxD11();$badLegacy->head=$legacy->head;$badLegacy->failLegacy=true;$badWriter=makeWriterD11($policy,$badLegacy);ok(rejects(fn()=>$badWriter->append($input,$context))&&end($badLegacy->calls)==='ROLLBACK','legacy_mismatch_rollback');
$empty=new FakeTxD11();$empty->head=['last_sequence_number'=>0,'last_event_hash'=>CanonicalAuditWriter::GENESIS_HASH,'hash_version'=>'sha256-hex-v1','updated_at'=>null];$emptyWriter=makeWriterD11($policy,$empty);$first=$emptyWriter->append($input,$context);ok($first->value('sequence_number')===1&&$first->value('previous_hash')===CanonicalAuditWriter::GENESIS_HASH,'new_empty_head');ok(!in_array('VERIFY_LEGACY_HEAD',$empty->calls,true),'new_head_not_legacy');
$invalidEmpty=new FakeTxD11();$invalidEmpty->head=['last_sequence_number'=>0,'last_event_hash'=>CanonicalAuditWriter::GENESIS_HASH,'hash_version'=>null,'updated_at'=>null];$invalidEmptyWriter=makeWriterD11($policy,$invalidEmpty);ok(rejects(fn()=>$invalidEmptyWriter->append($input,$context))&&end($invalidEmpty->calls)==='ROLLBACK','null_empty_rejected');
$mismatch=new FakeTxD11();$mismatch->head=['last_sequence_number'=>2,'last_event_hash'=>str_repeat('c',64),'hash_version'=>'future-v2','updated_at'=>'2026-08-13T23:00:00.000000Z'];$mismatchWriter=makeWriterD11($policy,$mismatch);ok(rejects(fn()=>$mismatchWriter->append($input,$context))&&end($mismatch->calls)==='ROLLBACK','known_version_mismatch_rollback');
$missingTime=new FakeTxD11();$missingTime->head=['last_sequence_number'=>2,'last_event_hash'=>str_repeat('c',64),'hash_version'=>null,'updated_at'=>null];$missingTimeWriter=makeWriterD11($policy,$missingTime);ok(rejects(fn()=>$missingTimeWriter->append($input,$context))&&end($missingTime->calls)==='ROLLBACK','legacy_missing_time_rollback');
$fail=new FakeTxD11();$fail->failUpdate=true;$failWriter=makeWriterD11($policy,$fail);ok(rejects(fn()=>$failWriter->append($input,$context))&&end($fail->calls)==='ROLLBACK','rowcount_rollback');
$props=array_map(fn($p)=>$p->getName(),(new ReflectionClass(CanonicalAuditEventInput::class))->getProperties());foreach(['event_id','occurred_at','created_at','sequence_number','previous_hash','event_hash','ip_hmac','ip_hmac_key_version','_audit_v1'] as $forbidden)ok(!in_array($forbidden,$props,true),'producer_cannot_'.$forbidden);
ok(rejects(fn()=>$writer->append(new CanonicalAuditEventInput('AUTH_LOGIN_SUCCEEDED','FAILURE','USER_REQUEST',null,null,'IDENTITY','x',[]),$context)),'invalid_pair');ok(rejects(fn()=>$writer->append(new CanonicalAuditEventInput('AUTH_LOGIN_SUCCEEDED','SUCCESS','USER_REQUEST',null,null,'IDENTITY','x',['raw_ip'=>'x']),$context)),'raw_metadata');
$short=new class implements AuditSecretProvider{public function currentAuditIpKey():array{return ['version'=>'v','secret'=>'short'];}};ok(rejects(fn()=>(new HmacSha256AuditIpHasher($short))->hashTrustedNetworkAddress('192.0.2.1')),'short_secret');$same=new HmacSha256AuditIpHasher(new FixedSecretD11());ok($same->hashTrustedNetworkAddress('192.0.2.1')===$same->hashTrustedNetworkAddress('192.0.2.1'),'hmac_deterministic');ok((new CoarseAuditUserAgentSummarizer())->summarizeTrustedUserAgent('')==='UNKNOWN|UNKNOWN|UNKNOWN','ua_unknown');
$pdo=file_get_contents(__DIR__.'/../repositories/PdoCanonicalAuditTransactionAdapter.php');ok(str_contains($pdo,'CALL `mxmed`.`audit_mp01c_lock_stream_head_v1`(:stream_key)'),'controlled_lock_call');ok(str_contains($pdo,'CALL `mxmed`.`audit_mp01c_advance_stream_head_cas_v1`'),'controlled_cas_call');
ok(!preg_match('/UPDATE\s+`?platform_audit_stream_heads/i',$pdo),'no_direct_head_update');ok(!preg_match('/SELECT[^;]+platform_audit_stream_heads[^;]+FOR UPDATE/is',$pdo),'no_direct_head_for_update');
ok(substr_count($pdo,'self::drainCallResults($s)')===2&&str_contains($pdo,'nextRowset()')&&str_contains($pdo,'closeCursor()'),'both_call_results_drained');ok(str_contains($pdo,'$second!==false')&&str_contains($pdo,"RuntimeException('unexpected_audit_head_row_count'"),'exact_lock_row_count');
ok(str_contains($pdo,"getCode()==='45000'")&&str_contains($pdo,"RuntimeException('head_update_failed'"),'cas_signal_mapped_fail_closed');ok(str_contains($pdo,'canonicalTime($row'),'lock_time_normalized');
foreach([':stream_key',':expected_sequence',':expected_hash',':expected_hash_version',':expected_updated_at',':new_sequence',':new_hash',':new_hash_version',':new_updated_at'] as $parameter)ok(str_contains($pdo,$parameter),'routine_parameter_'.$parameter);ok(str_contains($pdo,'assertLegacyHeadMatchesLatest')&&substr_count($pdo,'FOR SHARE')===2,'legacy_reads_preserved');
ok(!preg_match('/UPDATE\s+platform_audit_events\s+SET/i',$pdo),'no_history_update');ok(!preg_match('/DELETE\s+FROM\s+platform_audit_events/i',$pdo),'no_history_delete');ok(!preg_match('/REPLACE\s+INTO/i',$pdo),'no_replace');
$migration=file_get_contents(__DIR__.'/../db/migrations/2026_08_13_01_align_platform_audit_stream_heads_d11.sql');ok(str_contains($migration,'SET h.updated_at=e.created_at_utc'),'physical_updated_at_backfill');ok(!preg_match('/\bNOW\s*\(|\bCURRENT_TIMESTAMP\b/i',$migration),'no_migration_time');ok(!preg_match('/SET\s+h?\.?hash_version\s*=/i',$migration),'legacy_version_not_invented');
ok(substr_count($pdo,'SELECT stream_key,sequence_number,event_hash FROM platform_audit_events')===2,'d12_exact_three_column_selects');ok(!preg_match('/SELECT\s+\*/i',$pdo),'d12_no_select_star');ok(!preg_match('/SELECT[^;]+metadata_json[^;]+FROM\s+platform_audit_events/i',$pdo),'d12_no_extra_history_column');ok(count(array_filter($tx->calls,fn($v)=>$v==='VERIFY_LEGACY_HEAD'))===0,'versioned_append_zero_history_reads');ok(count(array_filter($legacy->calls,fn($v)=>$v==='VERIFY_LEGACY_HEAD'))===1,'legacy_append_authorized_history_verification');ok(str_contains($pdo,'FOR SHARE')&&!str_contains($pdo,'new PDO'),'d12_same_connection_shared_lock');ok(array_search('SELECT_HEAD_FOR_UPDATE',$legacy->calls,true)<array_search('VERIFY_LEGACY_HEAD',$legacy->calls,true)&&array_search('VERIFY_LEGACY_HEAD',$legacy->calls,true)<array_search('INSERT_EVENT',$legacy->calls,true),'d12_same_transaction_order');
$legacyHashes=[
    'modules/platform/adapters/PdoAuditTrailAdapter.php' => '34e5b71a523f92eb77f073acf42d5c3b2e37e0a810bc3795a33ab7350d2cd1e1',
    'modules/agenda/composition/AgendaAuthorityCompositionRoot.php' => '792db046323e94e1682342851771f7a27af330cc645e93302d3f4cb05dfb2023',
    'modules/agenda/security/AgendaActorAuthorityResolver.php' => '2b47a8d25d328c7f594ee40d7f86392f4b6ac87c4fb600349dfa5a9fac5df5a8',
    'modules/platform/services/AuthorizationBoundary.php' => '64b869dbfeab6614f14229ccaaa957b13d82284219a6fc359d1480b393fbb0d8',
    'modules/platform/services/BreakGlassAccessEvaluator.php' => 'c808213fe8b15f69d4896bf065adef05d4d41e9440c2075ded317d0ac8465320',
    'modules/platform/services/PrivilegedAccessPolicySupport.php' => 'a82230073222ece725e28241d8397b6f15f283c3000a1c6e1759fb34457d04f3',
    'modules/platform/services/SupportAssistedAccessEvaluator.php' => 'bc9aaba9ce9532a46978ec9ca99ac4c0270517185fbe4828b69eff523f418591',
];foreach($legacyHashes as $relative=>$wanted){$physical=$root.'/'.$relative;ok(is_file($physical)&&hash_file('sha256',$physical)===$wanted,'legacy_preserved_'.basename($relative));}
foreach(['D01_D10_REGRESSION_GROUP','TYPED_WRITER_PIPELINE_GROUP','SERVER_UUID_CLOCK_GROUP','HMAC_KEY_VERSION_GROUP','PDO_TRANSACTION_ADAPTER_GROUP','END_TO_END_CANONICAL_WRITER_GROUP','NO_WIRING_GROUP','SELF_CONTAINMENT_GROUP','D11_RATIFICATION_GROUP','LEGACY_BRIDGE_GROUP','KNOWN_VERSION_MISMATCH_GROUP','UPDATED_AT_BACKFILL_GROUP','D12_HISTORY_READ_SCOPE_GROUP','D01_D12_REGRESSION_GROUP','CANONICAL_POLICY_INTERNAL_AUTHORITY_GROUP','REPO_INSTALLED_TESTS_GROUP','SIMULATED_REPO_GROUP','LEGACY_PRESERVATION_SELF_CONTAINED_GROUP','NO_EXTERNAL_POLICY_GROUP'] as $group)echo "$group=PASS\n";
echo "UNIT_TESTS_TOTAL=$total\nUNIT_TESTS_PASS=$pass/$total\nUNIT_TESTS_FAIL=".($total-$pass)."\n";
