CREATE TABLE IF NOT EXISTS media_assets (
    media_id CHAR(36) NOT NULL,
    owner_type ENUM('PHYSICIAN','CONSULTORIO') NOT NULL,
    owner_id VARCHAR(191) NOT NULL,
    purpose ENUM('PHYSICIAN_PERSONAL_LOGO','CONSULTORIO_GROUP_LOGO') NOT NULL,
    classification ENUM('PUBLIC') NOT NULL,
    storage_key VARCHAR(512) NOT NULL,
    public_url VARCHAR(512) NOT NULL,
    mime_type ENUM('image/webp') NOT NULL,
    format ENUM('webp') NOT NULL,
    width INT UNSIGNED NOT NULL,
    height INT UNSIGNED NOT NULL,
    byte_size INT UNSIGNED NOT NULL,
    checksum_sha256 CHAR(64) NOT NULL,
    alt_text VARCHAR(255) NOT NULL,
    status ENUM('READY','DELETED') NOT NULL DEFAULT 'READY',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL,
    PRIMARY KEY (media_id),
    UNIQUE KEY uniq_media_assets_storage_key (storage_key),
    UNIQUE KEY uniq_media_assets_public_url (public_url),
    KEY idx_media_assets_owner_purpose_status (owner_type, owner_id, purpose, status),
    KEY idx_media_assets_owner_checksum (owner_type, owner_id, purpose, checksum_sha256),
    CONSTRAINT chk_media_assets_width CHECK (width > 0 AND width <= 800),
    CONSTRAINT chk_media_assets_height CHECK (height > 0 AND height <= 800),
    CONSTRAINT chk_media_assets_bytes CHECK (byte_size > 0 AND byte_size <= 153600),
    CONSTRAINT chk_media_assets_checksum CHECK (checksum_sha256 REGEXP '^[0-9a-f]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
