<?php
declare(strict_types=1);
namespace Platform\Services;
use Platform\Contracts\CanonicalAuditEventType;
final class CorrelatableOperationCatalog
{
    public const CHILD_CORRELATIONS_SUPPORTED=false;
    private const OPERATIONS=['AUTH_REGISTRATION','AUTH_EMAIL_VERIFICATION','AUTH_LOGIN','AUTH_PASSWORD_RECOVERY','AUTH_PASSWORD_CHANGE','AUTH_SESSION_LIFECYCLE','PROFILE_CLAIM','PROFILE_OWNERSHIP_TRANSFER','INVITATION_LIFECYCLE','ROLE_LIFECYCLE','STEP_UP_CHALLENGE','BREAK_GLASS_LIFECYCLE','SENSITIVE_ADMIN_OPERATION'];
    private const EVENT_MAP=['AUTH_REGISTRATION_REQUESTED'=>'AUTH_REGISTRATION','AUTH_EMAIL_VERIFICATION_SENT'=>'AUTH_EMAIL_VERIFICATION','AUTH_EMAIL_VERIFIED'=>'AUTH_EMAIL_VERIFICATION','AUTH_LOGIN_SUCCEEDED'=>'AUTH_LOGIN','AUTH_LOGIN_FAILED'=>'AUTH_LOGIN','AUTH_PASSWORD_RECOVERY_REQUESTED'=>'AUTH_PASSWORD_RECOVERY','AUTH_PASSWORD_RESET_SUCCEEDED'=>'AUTH_PASSWORD_RECOVERY','AUTH_PASSWORD_CHANGED'=>'AUTH_PASSWORD_CHANGE','AUTH_SESSION_CREATED'=>'AUTH_SESSION_LIFECYCLE','AUTH_SESSION_ROTATED'=>'AUTH_SESSION_LIFECYCLE','AUTH_SESSION_REVOKED'=>'AUTH_SESSION_LIFECYCLE','AUTH_LOGOUT'=>'AUTH_SESSION_LIFECYCLE','AUTH_LOGOUT_ALL'=>'AUTH_SESSION_LIFECYCLE','PROFILE_CLAIM_REQUESTED'=>'PROFILE_CLAIM','PROFILE_CLAIM_APPROVED'=>'PROFILE_CLAIM','PROFILE_CLAIM_REJECTED'=>'PROFILE_CLAIM','PROFILE_OWNERSHIP_ASSIGNED'=>'PROFILE_OWNERSHIP_TRANSFER','PROFILE_OWNERSHIP_TRANSFERRED'=>'PROFILE_OWNERSHIP_TRANSFER','INVITATION_CREATED'=>'INVITATION_LIFECYCLE','INVITATION_ACCEPTED'=>'INVITATION_LIFECYCLE','INVITATION_REVOKED'=>'INVITATION_LIFECYCLE','ROLE_ASSIGNED'=>'ROLE_LIFECYCLE','ROLE_REVOKED'=>'ROLE_LIFECYCLE','STEP_UP_CHALLENGE_SUCCEEDED'=>'STEP_UP_CHALLENGE','STEP_UP_CHALLENGE_FAILED'=>'STEP_UP_CHALLENGE','BREAK_GLASS_STARTED'=>'BREAK_GLASS_LIFECYCLE','BREAK_GLASS_ENDED'=>'BREAK_GLASS_LIFECYCLE','SENSITIVE_ADMIN_ACTION'=>'SENSITIVE_ADMIN_OPERATION'];
    public function __construct(){if(count(self::OPERATIONS)!==13||count(self::EVENT_MAP)!==28||array_keys(self::EVENT_MAP)!==CanonicalAuditEventType::all())throw new \LogicException('invalid_operation_catalog');}
    public function all():array{return self::OPERATIONS;} public function eventMap():array{return self::EVENT_MAP;}
    public function operationForEvent(string $eventType):string{CanonicalAuditEventType::assertKnown($eventType);return self::EVENT_MAP[$eventType];}
    public function assertContinuable(string $operation):void{if(!in_array($operation,self::OPERATIONS,true))throw new \InvalidArgumentException('uncatalogued_operation_cannot_continue');}
    public function assertStartable(string $operation):void{if(preg_match('/^[A-Z][A-Z0-9_]{2,63}$/D',$operation)!==1)throw new \InvalidArgumentException('invalid_operation_key');}
}
