import type { MxMedEnvironmentConfig, MxMedEnvironmentName } from './environment-config';
import {
  parseEnvironmentName,
  validateEnvironmentConfig,
  validateEnvironmentNetworkSeparation,
} from './environment-schema';

export const STAGING_CONFIG = Object.freeze({
  environmentName: 'staging',
  environmentCode: 'stg',
  projectName: 'mxmed',
  applicationName: 'mexico-medico',
  primaryRegion: 'mx-central-1',
  emailRegion: 'us-east-1',
  accountSource: 'deployment-identity',
  vpcCidr: '10.20.0.0/16',
  subnetMasks: {
    publicIngress: 24,
    privateApp: 20,
    privateEndpoints: 24,
    isolatedData: 24,
  },
  availabilityZoneCount: 2,
  natStrategy: 'single-az',
  interfaceEndpointProfile: 's3-only',
  flowLogRetentionDays: 30,
  securityProfile: 'baseline-v1',
  kmsDeletionWindowDays: 7,
  secretRecoveryWindowDays: 7,
  cloudTrailLogRetentionDays: 90,
  auditArchiveRetentionDays: 365,
  enableManagementTrail: true,
  enableKeyRotation: true,
  enableDataEventTrail: false,
  computeSizingProfile: 'reduced',
  databaseEngine: 'mysql',
  databaseEngineVersion: '8.4.9',
  databaseParameterGroupFamily: 'mysql8.4',
  databaseInstanceClass: 'db.t4g.medium',
  databaseMultiAz: false,
  databaseAllocatedStorageGiB: 40,
  databaseMaxAllocatedStorageGiB: 200,
  databaseStorageType: 'gp3',
  databaseIops: 3000,
  databaseStorageThroughput: 125,
  databaseBackupRetentionDays: 7,
  databaseDeletionProtection: false,
  databaseInsightsMode: 'standard',
  databaseEnhancedMonitoringIntervalSeconds: 60,
  databasePreferredBackupWindow: '00:00-00:30',
  databasePreferredMaintenanceWindow: 'sun:01:30-sun:02:30',
  databaseCloudWatchLogsExports: ['error', 'slowquery'],
  databaseName: 'mxmed',
  databaseMasterUsername: 'mxmed_admin',
  databaseCharacterSet: 'utf8mb4',
  databaseCollation: 'utf8mb4_unicode_ci',
  databaseEngineLifecycleSupport: 'open-source-rds-extended-support-disabled',
  logRetentionDays: 30,
  backupRetentionDays: 7,
  enableDeletionProtection: false,
  enableTerminationProtection: false,
  enableWaf: true,
  enableCloudFrontLogging: true,
  stripeReturnLoggingPolicy: 'path-only-no-query',
  tags: {
    Project: 'mxmed',
    Environment: 'staging',
    ManagedBy: 'aws-cdk',
    Application: 'mexico-medico',
    Owner: 'platform',
  },
} satisfies MxMedEnvironmentConfig);

export const PRODUCTION_CONFIG = Object.freeze({
  environmentName: 'production',
  environmentCode: 'prd',
  projectName: 'mxmed',
  applicationName: 'mexico-medico',
  primaryRegion: 'mx-central-1',
  emailRegion: 'us-east-1',
  accountSource: 'deployment-identity',
  vpcCidr: '10.30.0.0/16',
  subnetMasks: {
    publicIngress: 24,
    privateApp: 20,
    privateEndpoints: 24,
    isolatedData: 24,
  },
  availabilityZoneCount: 2,
  natStrategy: 'dual-az',
  interfaceEndpointProfile: 'production-core',
  flowLogRetentionDays: 90,
  securityProfile: 'baseline-v1',
  kmsDeletionWindowDays: 30,
  secretRecoveryWindowDays: 30,
  cloudTrailLogRetentionDays: 365,
  auditArchiveRetentionDays: 2555,
  enableManagementTrail: true,
  enableKeyRotation: true,
  enableDataEventTrail: false,
  computeSizingProfile: 'production-ha',
  databaseEngine: 'mysql',
  databaseEngineVersion: '8.4.9',
  databaseParameterGroupFamily: 'mysql8.4',
  databaseInstanceClass: 'db.m6g.large',
  databaseMultiAz: true,
  databaseAllocatedStorageGiB: 100,
  databaseMaxAllocatedStorageGiB: 1000,
  databaseStorageType: 'gp3',
  databaseIops: 3000,
  databaseStorageThroughput: 125,
  databaseBackupRetentionDays: 35,
  databaseDeletionProtection: true,
  databaseInsightsMode: 'standard',
  databaseEnhancedMonitoringIntervalSeconds: 15,
  databasePreferredBackupWindow: '00:30-01:00',
  databasePreferredMaintenanceWindow: 'sun:02:30-sun:03:30',
  databaseCloudWatchLogsExports: ['error', 'slowquery'],
  databaseName: 'mxmed',
  databaseMasterUsername: 'mxmed_admin',
  databaseCharacterSet: 'utf8mb4',
  databaseCollation: 'utf8mb4_unicode_ci',
  databaseEngineLifecycleSupport: 'open-source-rds-extended-support-disabled',
  logRetentionDays: 90,
  backupRetentionDays: 35,
  enableDeletionProtection: true,
  enableTerminationProtection: true,
  enableWaf: true,
  enableCloudFrontLogging: true,
  stripeReturnLoggingPolicy: 'path-only-no-query',
  tags: {
    Project: 'mxmed',
    Environment: 'production',
    ManagedBy: 'aws-cdk',
    Application: 'mexico-medico',
    Owner: 'platform',
  },
} satisfies MxMedEnvironmentConfig);

validateEnvironmentConfig(STAGING_CONFIG);
validateEnvironmentConfig(PRODUCTION_CONFIG);
validateEnvironmentNetworkSeparation(STAGING_CONFIG, PRODUCTION_CONFIG);

const ENVIRONMENTS: Readonly<Record<MxMedEnvironmentName, MxMedEnvironmentConfig>> = {
  staging: STAGING_CONFIG,
  production: PRODUCTION_CONFIG,
};

export function getEnvironmentConfig(value: unknown): MxMedEnvironmentConfig {
  const environmentName = parseEnvironmentName(value);
  const config = ENVIRONMENTS[environmentName];
  validateEnvironmentConfig(config);
  return config;
}
