import type {
  MxMedComputeActivationMode,
  MxMedEnvironmentConfig,
  MxMedEnvironmentName,
} from './environment-config';
import {
  computeEcrRetention,
  MXMED_COMPUTE_RUNTIME_CONTRACT,
  resolveComputeControls,
} from './compute-config';
import {
  parseEnvironmentName,
  validateEnvironmentConfig,
  validateEnvironmentNetworkSeparation,
} from './environment-schema';
import {
  MXMED_COST_AWARE_LAUNCH_PROFILES_CONTRACT,
  MXMED_COST_ESTIMATE_AS_OF,
  resolveLaunchProfile,
} from './launch-profiles';
import type { MxMedEdgeContextValues } from './edge-config';
import { MXMED_REAL_EDGE_RUNTIME_GATES, resolveEdgeContext } from './edge-config';
import type { MxMedOperationsContextValues } from './operations-profiles';
import { resolveOperationsContext } from './operations-profiles';
import type { MxMedBackupDrContextValues } from './backup-dr-profiles';
import { resolveBackupDrContext } from './backup-dr-profiles';

const STAGING_BASE_CONFIG = Object.freeze({
  environmentName: 'staging',
  environmentCode: 'stg',
  projectName: 'mxmed',
  applicationName: 'mexico-medico',
  primaryRegion: 'mx-central-1',
  emailRegion: 'us-east-1',
  accountSource: 'deployment-identity',
  vpcCidr: '10.20.0.0/16',
  subnetMasks: {
    publicIngress: 24,
    privateApp: 20,
    privateEndpoints: 24,
    isolatedData: 24,
  },
  availabilityZoneCount: 2,
  natStrategy: 'single-az',
  interfaceEndpointProfile: 's3-only',
  flowLogRetentionDays: 30,
  securityProfile: 'baseline-v1',
  kmsDeletionWindowDays: 7,
  secretRecoveryWindowDays: 7,
  cloudTrailLogRetentionDays: 90,
  auditArchiveRetentionDays: 365,
  enableManagementTrail: true,
  enableKeyRotation: true,
  enableDataEventTrail: false,
  computeSizingProfile: 'reduced',
  databaseEngine: 'mysql',
  databaseEngineVersion: '8.4.9',
  databaseParameterGroupFamily: 'mysql8.4',
  databaseInstanceClass: 'db.t4g.medium',
  databaseMultiAz: false,
  databaseAllocatedStorageGiB: 40,
  databaseMaxAllocatedStorageGiB: 200,
  databaseStorageType: 'gp3',
  databaseIops: 3000,
  databaseStorageThroughput: 125,
  databaseBackupRetentionDays: 7,
  databaseDeletionProtection: false,
  databaseInsightsMode: 'standard',
  databaseEnhancedMonitoringIntervalSeconds: 60,
  databasePreferredBackupWindow: '00:00-00:30',
  databasePreferredMaintenanceWindow: 'sun:01:30-sun:02:30',
  databaseCloudWatchLogsExports: ['error', 'slowquery'],
  databaseName: 'mxmed',
  databaseMasterUsername: 'mxmed_admin',
  databaseCharacterSet: 'utf8mb4',
  databaseCollation: 'utf8mb4_unicode_ci',
  databaseEngineLifecycleSupport: 'open-source-rds-extended-support-disabled',
  storageProfile: 'storage-foundation-v1',
  storageVersioningEnabled: true,
  storageEncryptionProfile: 'application-data-kms',
  storageBucketKeyEnabled: true,
  publicMediaNoncurrentRetentionDays: 30,
  privateDocumentsNoncurrentRetentionDays: 30,
  clinicalNoncurrentRetentionDays: 30,
  quarantinePendingRetentionDays: 7,
  quarantineFailedRetentionDays: 14,
  quarantineInfectedRetentionDays: 30,
  quarantineCleanRetentionDays: 1,
  temporaryExportRetentionDays: 7,
  privateStorageTransitionDays: null,
  clinicalStorageTransitionDays: null,
  uploadUrlTtlSeconds: 600,
  downloadUrlTtlSeconds: 300,
  publicMediaMaxUploadMiB: 20,
  publicMediaMaxDerivedMiB: 10,
  privateMaxUploadMiB: 100,
  clinicalMaxUploadMiB: 100,
  enableQuarantineEventBridge: true,
  enableObjectLock: false,
  enableCrossRegionReplication: false,
  enableStorageDataEvents: false,
  storageAllowedMimeTypes: {
    public: ['image/jpeg', 'image/png', 'image/webp'],
    private: ['application/pdf', 'image/jpeg', 'image/png', 'image/webp'],
    clinical: ['application/pdf', 'image/jpeg', 'image/png', 'image/webp'],
  },
  sessionProfile: 'session-foundation-v1',
  sessionEngine: 'valkey',
  sessionEngineVersion: '8.2',
  sessionNodeType: 'cache.t4g.micro',
  sessionClusterModeEnabled: false,
  sessionShardCount: 1,
  sessionReplicaCount: 0,
  sessionMultiAzEnabled: false,
  sessionAutomaticFailoverEnabled: false,
  sessionAtRestEncryptionEnabled: true,
  sessionTransitEncryptionEnabled: true,
  sessionTransitEncryptionMode: 'create-time-tls-only',
  sessionIdleTtlSeconds: 3600,
  sessionAbsoluteLifetimeSeconds: 43200,
  sessionMaxPayloadKiB: 32,
  sessionSnapshotRetentionDays: 0,
  sessionAutoMinorVersionUpgrade: false,
  sessionPreferredMaintenanceWindow: 'sun:03:30-sun:04:30',
  sessionParameterGroupFamily: 'valkey8',
  sessionAuthProfile: 'valkey-rbac-password-v1',
  sessionAclKeyPattern: '~mxmed:stg:session:*',
  sessionLockEnabled: true,
  sessionLockTimeoutSeconds: 10,
  sessionLockWaitMicroseconds: 100000,
  sessionLogDeliveryEnabled: false,
  logRetentionDays: 30,
  backupRetentionDays: 7,
  enableDeletionProtection: false,
  enableTerminationProtection: false,
  enableWaf: true,
  enableCloudFrontLogging: true,
  stripeReturnLoggingPolicy: 'path-only-no-query',
  tags: {
    Project: 'mxmed',
    Environment: 'staging',
    ManagedBy: 'aws-cdk',
    Application: 'mexico-medico',
    Owner: 'platform',
  },
});

const PRODUCTION_BASE_CONFIG = Object.freeze({
  environmentName: 'production',
  environmentCode: 'prd',
  projectName: 'mxmed',
  applicationName: 'mexico-medico',
  primaryRegion: 'mx-central-1',
  emailRegion: 'us-east-1',
  accountSource: 'deployment-identity',
  vpcCidr: '10.30.0.0/16',
  subnetMasks: {
    publicIngress: 24,
    privateApp: 20,
    privateEndpoints: 24,
    isolatedData: 24,
  },
  availabilityZoneCount: 2,
  natStrategy: 'dual-az',
  interfaceEndpointProfile: 'production-core',
  flowLogRetentionDays: 90,
  securityProfile: 'baseline-v1',
  kmsDeletionWindowDays: 30,
  secretRecoveryWindowDays: 30,
  cloudTrailLogRetentionDays: 365,
  auditArchiveRetentionDays: 2555,
  enableManagementTrail: true,
  enableKeyRotation: true,
  enableDataEventTrail: false,
  computeSizingProfile: 'production-ha',
  databaseEngine: 'mysql',
  databaseEngineVersion: '8.4.9',
  databaseParameterGroupFamily: 'mysql8.4',
  databaseInstanceClass: 'db.m6g.large',
  databaseMultiAz: true,
  databaseAllocatedStorageGiB: 100,
  databaseMaxAllocatedStorageGiB: 1000,
  databaseStorageType: 'gp3',
  databaseIops: 3000,
  databaseStorageThroughput: 125,
  databaseBackupRetentionDays: 35,
  databaseDeletionProtection: true,
  databaseInsightsMode: 'standard',
  databaseEnhancedMonitoringIntervalSeconds: 15,
  databasePreferredBackupWindow: '00:30-01:00',
  databasePreferredMaintenanceWindow: 'sun:02:30-sun:03:30',
  databaseCloudWatchLogsExports: ['error', 'slowquery'],
  databaseName: 'mxmed',
  databaseMasterUsername: 'mxmed_admin',
  databaseCharacterSet: 'utf8mb4',
  databaseCollation: 'utf8mb4_unicode_ci',
  databaseEngineLifecycleSupport: 'open-source-rds-extended-support-disabled',
  storageProfile: 'storage-foundation-v1',
  storageVersioningEnabled: true,
  storageEncryptionProfile: 'application-data-kms',
  storageBucketKeyEnabled: true,
  publicMediaNoncurrentRetentionDays: 90,
  privateDocumentsNoncurrentRetentionDays: null,
  clinicalNoncurrentRetentionDays: null,
  quarantinePendingRetentionDays: 7,
  quarantineFailedRetentionDays: 14,
  quarantineInfectedRetentionDays: 30,
  quarantineCleanRetentionDays: 1,
  temporaryExportRetentionDays: 7,
  privateStorageTransitionDays: 30,
  clinicalStorageTransitionDays: 30,
  uploadUrlTtlSeconds: 600,
  downloadUrlTtlSeconds: 300,
  publicMediaMaxUploadMiB: 20,
  publicMediaMaxDerivedMiB: 10,
  privateMaxUploadMiB: 100,
  clinicalMaxUploadMiB: 100,
  enableQuarantineEventBridge: true,
  enableObjectLock: false,
  enableCrossRegionReplication: false,
  enableStorageDataEvents: false,
  storageAllowedMimeTypes: {
    public: ['image/jpeg', 'image/png', 'image/webp'],
    private: ['application/pdf', 'image/jpeg', 'image/png', 'image/webp'],
    clinical: ['application/pdf', 'image/jpeg', 'image/png', 'image/webp'],
  },
  sessionProfile: 'session-foundation-v1',
  sessionEngine: 'valkey',
  sessionEngineVersion: '8.2',
  sessionNodeType: 'cache.t4g.medium',
  sessionClusterModeEnabled: false,
  sessionShardCount: 1,
  sessionReplicaCount: 1,
  sessionMultiAzEnabled: true,
  sessionAutomaticFailoverEnabled: true,
  sessionAtRestEncryptionEnabled: true,
  sessionTransitEncryptionEnabled: true,
  sessionTransitEncryptionMode: 'create-time-tls-only',
  sessionIdleTtlSeconds: 3600,
  sessionAbsoluteLifetimeSeconds: 43200,
  sessionMaxPayloadKiB: 32,
  sessionSnapshotRetentionDays: 0,
  sessionAutoMinorVersionUpgrade: false,
  sessionPreferredMaintenanceWindow: 'sun:04:30-sun:05:30',
  sessionParameterGroupFamily: 'valkey8',
  sessionAuthProfile: 'valkey-rbac-password-v1',
  sessionAclKeyPattern: '~mxmed:prd:session:*',
  sessionLockEnabled: true,
  sessionLockTimeoutSeconds: 10,
  sessionLockWaitMicroseconds: 100000,
  sessionLogDeliveryEnabled: false,
  logRetentionDays: 90,
  backupRetentionDays: 35,
  enableDeletionProtection: true,
  enableTerminationProtection: true,
  enableWaf: true,
  enableCloudFrontLogging: true,
  stripeReturnLoggingPolicy: 'path-only-no-query',
  tags: {
    Project: 'mxmed',
    Environment: 'production',
    ManagedBy: 'aws-cdk',
    Application: 'mexico-medico',
    Owner: 'platform',
  },
});

function createEnvironmentConfig(
  environmentName: MxMedEnvironmentName,
  deploymentProfileValue: unknown,
  computeActivationModeValue: unknown = 'disabled-v1' satisfies MxMedComputeActivationMode,
  runtimeCapabilityProfileValue?: unknown,
  edgeContextValues: MxMedEdgeContextValues = {},
  operationsContextValues: MxMedOperationsContextValues = {},
  backupDrContextValues: MxMedBackupDrContextValues = {},
): MxMedEnvironmentConfig {
  const resolved = resolveLaunchProfile(environmentName, deploymentProfileValue);
  const computeControls = resolveComputeControls(
    computeActivationModeValue,
    runtimeCapabilityProfileValue,
  );
  const ecrRetention = computeEcrRetention(environmentName, resolved.deploymentProfile);
  const base = environmentName === 'staging' ? STAGING_BASE_CONFIG : PRODUCTION_BASE_CONFIG;
  const edge = resolveEdgeContext(edgeContextValues);
  const operations = resolveOperationsContext(
    environmentName,
    resolved.deploymentProfile,
    operationsContextValues,
  );
  const backupDr = resolveBackupDrContext(backupDrContextValues);
  const backupActive = backupDr.backupDrActivationMode !== 'disabled-v1';
  const databaseBackupRetentionDays = backupActive ? 35 : base.databaseBackupRetentionDays;
  const config = {
    ...base,
    ...resolved.capacity,
    deploymentProfile: resolved.deploymentProfile,
    stagingOperatingMode: resolved.stagingOperatingMode,
    computeActivationMode: computeControls.activationMode,
    runtimeCapabilityProfile: computeControls.runtimeCapabilityProfile,
    computePlatformVersion: MXMED_COMPUTE_RUNTIME_CONTRACT.platformVersion,
    computePhpMajorVersion: MXMED_COMPUTE_RUNTIME_CONTRACT.phpMajorVersion,
    computeApacheEnabled: MXMED_COMPUTE_RUNTIME_CONTRACT.apacheEnabled,
    computeModRewriteEnabled: MXMED_COMPUTE_RUNTIME_CONTRACT.modRewriteEnabled,
    computeDocumentRoot: MXMED_COMPUTE_RUNTIME_CONTRACT.documentRoot,
    computeContainerPort: MXMED_COMPUTE_RUNTIME_CONTRACT.containerPort,
    computeEphemeralStorageGiB: MXMED_COMPUTE_RUNTIME_CONTRACT.ephemeralStorageGiB,
    computeHealthPath: MXMED_COMPUTE_RUNTIME_CONTRACT.healthPath,
    computeReadinessPath: MXMED_COMPUTE_RUNTIME_CONTRACT.readinessPath,
    computeCpuTargetPercent: MXMED_COMPUTE_RUNTIME_CONTRACT.cpuTargetPercent,
    computeMemoryTargetPercent: MXMED_COMPUTE_RUNTIME_CONTRACT.memoryTargetPercent,
    computeScaleOutCooldownSeconds: MXMED_COMPUTE_RUNTIME_CONTRACT.scaleOutCooldownSeconds,
    computeScaleInCooldownSeconds: MXMED_COMPUTE_RUNTIME_CONTRACT.scaleInCooldownSeconds,
    computeLogRetentionDays: environmentName === 'staging' ? 30 : 90,
    computeEcsExecEnabled: MXMED_COMPUTE_RUNTIME_CONTRACT.ecsExecEnabled,
    computeReadonlyRootFilesystem: MXMED_COMPUTE_RUNTIME_CONTRACT.readonlyRootFilesystem,
    computeImageScanOnPush: MXMED_COMPUTE_RUNTIME_CONTRACT.imageScanOnPush,
    computeImageTagImmutable: MXMED_COMPUTE_RUNTIME_CONTRACT.imageTagImmutable,
    computeEcrUntaggedRetentionDays: ecrRetention.untaggedDays,
    computeEcrMaxImageCount: ecrRetention.maxImages,
    computeMigrationCommandMode: MXMED_COMPUTE_RUNTIME_CONTRACT.migrationCommandMode,
    ...edge,
    ...MXMED_REAL_EDGE_RUNTIME_GATES,
    ...operations,
    ...backupDr,
    databaseBackupRetentionDays,
    backupRetentionDays: databaseBackupRetentionDays,
    cloudFrontPricingPlanVerification: {
      expectedProfile: edge.edgePricingProfile,
      accountEligibilityVerified: false,
      planAttached: false,
      verifiedAt: null,
      verificationEvidenceReference: null,
    },
    approvedMonthlyBudgetUsd: null,
    planningFxMxnPerUsd: null,
    planningFxAsOf: null,
    anomalyAlertThresholdUsd: null,
    maxInfrastructureCostToRevenuePercent: null,
    budgetOwner: null,
    alertRecipientsConfigured: false,
    costReadinessReviewApproved: false,
    costEstimateAsOf: MXMED_COST_ESTIMATE_AS_OF,
    costEstimateVersion: MXMED_COST_AWARE_LAUNCH_PROFILES_CONTRACT,
    enableCostBudgets: false,
    enableCostAnomalyDetection: false,
    enableStagingSchedule: false,
    stagingReleaseWindowHours: null,
    costAlertThresholdPercentages: [50, 75, 90, 100, 120],
    profilePromotionPolicyVersion: MXMED_COST_AWARE_LAUNCH_PROFILES_CONTRACT,
    tags: {
      Project: 'mxmed',
      Environment: environmentName,
      ManagedBy: 'aws-cdk',
      Application: 'mexico-medico',
      Owner: 'platform',
      DeploymentProfile: resolved.deploymentProfile,
      CostReview: MXMED_COST_ESTIMATE_AS_OF,
      Ephemeral: environmentName === 'staging' ? 'true' : 'false',
      SchedulePolicy: environmentName === 'staging' ? 'release-window-v1' : 'always-on',
      CostScope: environmentName === 'staging' ? 'mxmed-staging' : 'mxmed-production',
    },
  } as const;
  validateEnvironmentConfig(config);
  return Object.freeze(config);
}

export const STAGING_CONFIG = createEnvironmentConfig('staging', 'launch-lean-v1');
export const PRODUCTION_CONFIG = createEnvironmentConfig('production', 'launch-lean-v1');

validateEnvironmentNetworkSeparation(STAGING_CONFIG, PRODUCTION_CONFIG);

export function getEnvironmentConfig(
  value: unknown,
  deploymentProfileValue: unknown,
  computeActivationModeValue: unknown = 'disabled-v1',
  runtimeCapabilityProfileValue?: unknown,
  edgeContextValues: MxMedEdgeContextValues = {},
  operationsContextValues: MxMedOperationsContextValues = {},
  backupDrContextValues: MxMedBackupDrContextValues = {},
): MxMedEnvironmentConfig {
  const environmentName = parseEnvironmentName(value);
  return createEnvironmentConfig(
    environmentName,
    deploymentProfileValue,
    computeActivationModeValue,
    runtimeCapabilityProfileValue,
    edgeContextValues,
    operationsContextValues,
    backupDrContextValues,
  );
}
